const { __ } = wp.i18n;
import BaseField from "./BaseField";
import SelectField from "./SelectField";
import UnitField from "./UnitField";

const TypographyField = (props) => {
  const {
    value = {},
    options = [
      "fontFamily",
      "fontWeight",
      "fontSize",
      "lineHeight",
      "letterSpacing",
    ],
    onChange,
  } = props;

  const handleUpdateFont = (key, val) => {
    let updatedValue = { ...value };
    if ("object" === typeof key) {
      updatedValue = { ...value, ...key };
    } else {
      updatedValue[key] = val;
    }
    onChange(updatedValue);
  };

  const allFonts = [
    {
      id: "standard",
      label: __("Standard Fonts", "ditty-news-ticker"),
      fonts: [
        { name: "Arial", typeface: "sans-serif" },
        { name: "Arial Black", typeface: "sans-serif" },
        { name: "Courier New", typeface: "serif" },
        { name: "Georgia", typeface: "serif" },
        { name: "Times New Roman", typeface: "serif" },
        { name: "Trebuchet MS", typeface: "sans-serif" },
        { name: "Verdana", typeface: "sans-serif" },
        { name: "Impact", typeface: "sans-serif" },
        { name: "Lucida Console", typeface: "monospace" },
        { name: "Tahoma", typeface: "sans-serif" },
        { name: "Lucida Sans Unicode", typeface: "sans-serif" },
        { name: "Palatino Linotype", typeface: "serif" },
        { name: "Comic Sans MS", typeface: "sans-serif" },
      ],
    },
  ];

  if (dittyEditorVars.googleFonts) {
    allFonts.push({
      id: "google",
      label: __("Google Fonts", "ditty-news-ticker"),
      fonts: [
        { name: "ABeeZee", typeface: "sans-serif" },
        { name: "Abel", typeface: "sans-serif" },
        { name: "Abril Fatface", typeface: "serif" },
        { name: "Aclonica", typeface: "sans-serif" },
        { name: "Acme", typeface: "sans-serif" },
        { name: "Actor", typeface: "sans-serif" },
        { name: "Adamina", typeface: "serif" },
        { name: "Advent Pro", typeface: "sans-serif" },
        { name: "Aguafina Script", typeface: "serif" },
        { name: "Akronim", typeface: "serif" },
        { name: "Aladin", typeface: "serif" },
        { name: "Aldrich", typeface: "sans-serif" },
        { name: "Alef", typeface: "sans-serif" },
        { name: "Alegreya", typeface: "serif" },
        { name: "Alegreya SC", typeface: "serif" },
        { name: "Alegreya Sans", typeface: "sans-serif" },
        { name: "Alegreya Sans SC", typeface: "sans-serif" },
        { name: "Alex Brush", typeface: "serif" },
        { name: "Alfa Slab One", typeface: "serif" },
        { name: "Alice", typeface: "serif" },
        { name: "Alike", typeface: "serif" },
        { name: "Alike Angular", typeface: "serif" },
        { name: "Allan", typeface: "sans-serif" },
        { name: "Allerta", typeface: "sans-serif" },
        { name: "Allerta Stencil", typeface: "sans-serif" },
        { name: "Allura", typeface: "serif" },
        { name: "Almendra", typeface: "serif" },
        { name: "Almendra Display", typeface: "serif" },
        { name: "Almendra SC", typeface: "serif" },
        { name: "Amarante", typeface: "serif" },
        { name: "Amaranth", typeface: "sans-serif" },
        { name: "Amatic SC", typeface: "serif" },
        { name: "Amethysta", typeface: "serif" },
        { name: "Amiri", typeface: "serif" },
        { name: "Anaheim", typeface: "sans-serif" },
        { name: "Andada", typeface: "serif" },
        { name: "Andika", typeface: "sans-serif" },
        { name: "Angkor", typeface: "sans-serif" },
        { name: "Annie Use Your Telescope", typeface: "serif" },
        { name: "Anonymous Pro", typeface: "sans-serif" },
        { name: "Antic", typeface: "sans-serif" },
        { name: "Antic Didone", typeface: "serif" },
        { name: "Antic Slab", typeface: "serif" },
        { name: "Anton", typeface: "sans-serif" },
        { name: "Arapey", typeface: "serif" },
        { name: "Arbutus", typeface: "serif" },
        { name: "Arbutus Slab", typeface: "serif" },
        { name: "Architects Daughter", typeface: "sans-serif" },
        { name: "Archivo Black", typeface: "sans-serif" },
        { name: "Archivo Narrow", typeface: "sans-serif" },
        { name: "Arimo", typeface: "sans-serif" },
        { name: "Arizonia", typeface: "serif" },
        { name: "Armata", typeface: "sans-serif" },
        { name: "Artifika", typeface: "serif" },
        { name: "Arvo", typeface: "serif" },
        { name: "Asap", typeface: "sans-serif" },
        { name: "Asset", typeface: "sans-serif" },
        { name: "Astloch", typeface: "serif" },
        { name: "Asul", typeface: "sans-serif" },
        { name: "Atomic Age", typeface: "sans-serif" },
        { name: "Aubrey", typeface: "serif" },
        { name: "Audiowide", typeface: "sans-serif" },
        { name: "Autour One", typeface: "serif" },
        { name: "Average", typeface: "serif" },
        { name: "Average Sans", typeface: "sans-serif" },
        { name: "Averia Gruesa Libre", typeface: "sans-serif" },
        { name: "Averia Libre", typeface: "serif" },
        { name: "Averia Sans Libre", typeface: "sans-serif" },
        { name: "Averia Serif Libre", typeface: "serif" },
        { name: "Bad Script", typeface: "serif" },
        { name: "Balthazar", typeface: "serif" },
        { name: "Bangers", typeface: "sans-serif" },
        { name: "Basic", typeface: "sans-serif" },
        { name: "Battambang", typeface: "sans-serif" },
        { name: "Baumans", typeface: "sans-serif" },
        { name: "Bayon", typeface: "sans-serif" },
        { name: "Belgrano", typeface: "serif" },
        { name: "Belleza", typeface: "sans-serif" },
        { name: "BenchNine", typeface: "sans-serif" },
        { name: "Bentham", typeface: "serif" },
        { name: "Berkshire Swash", typeface: "serif" },
        { name: "Bevan", typeface: "serif" },
        { name: "Bigelow Rules", typeface: "sans-serif" },
        { name: "Bigshot One", typeface: "sans-serif" },
        { name: "Bilbo", typeface: "serif" },
        { name: "Bilbo Swash Caps", typeface: "serif" },
        { name: "Biryani", typeface: "sans-serif" },
        { name: "Bitter", typeface: "serif" },
        { name: "Black Ops One", typeface: "sans-serif" },
        { name: "Bokor", typeface: "sans-serif" },
        { name: "Bonbon", typeface: "serif" },
        { name: "Boogaloo", typeface: "sans-serif" },
        { name: "Bowlby One", typeface: "sans-serif" },
        { name: "Bowlby One SC", typeface: "sans-serif" },
        { name: "Brawler", typeface: "serif" },
        { name: "Bree Serif", typeface: "serif" },
        { name: "Bubblegum Sans", typeface: "sans-serif" },
        { name: "Bubbler One", typeface: "sans-serif" },
        { name: "Buda", typeface: "sans-serif" },
        { name: "Buenard", typeface: "serif" },
        { name: "Butcherman", typeface: "serif" },
        { name: "Butterfly Kids", typeface: "serif" },
        { name: "Cabin", typeface: "sans-serif" },
        { name: "Cabin Condensed", typeface: "sans-serif" },
        { name: "Cabin Sketch", typeface: "sans-serif" },
        { name: "Caesar Dressing", typeface: "serif" },
        { name: "Cagliostro", typeface: "sans-serif" },
        { name: "Calligraffitti", typeface: "serif" },
        { name: "Cambay", typeface: "sans-serif" },
        { name: "Cambo", typeface: "serif" },
        { name: "Candal", typeface: "sans-serif" },
        { name: "Cantarell", typeface: "sans-serif" },
        { name: "Cantata One", typeface: "serif" },
        { name: "Cantora One", typeface: "sans-serif" },
        { name: "Capriola", typeface: "sans-serif" },
        { name: "Cardo", typeface: "serif" },
        { name: "Carme", typeface: "sans-serif" },
        { name: "Carrois Gothic", typeface: "sans-serif" },
        { name: "Carrois Gothic SC", typeface: "sans-serif" },
        { name: "Carter One", typeface: "sans-serif" },
        { name: "Caudex", typeface: "serif" },
        { name: "Cedarville Cursive", typeface: "serif" },
        { name: "Ceviche One", typeface: "serif" },
        { name: "Changa One", typeface: "sans-serif" },
        { name: "Chango", typeface: "serif" },
        { name: "Chau Philomene One", typeface: "sans-serif" },
        { name: "Chela One", typeface: "sans-serif" },
        { name: "Chelsea Market", typeface: "sans-serif" },
        { name: "Chenla", typeface: "serif" },
        { name: "Cherry Cream Soda", typeface: "sans-serif" },
        { name: "Cherry Swash", typeface: "serif" },
        { name: "Chewy", typeface: "sans-serif" },
        { name: "Chicle", typeface: "serif" },
        { name: "Chivo", typeface: "sans-serif" },
        { name: "Cinzel", typeface: "serif" },
        { name: "Cinzel Decorative", typeface: "serif" },
        { name: "Clicker Script", typeface: "serif" },
        { name: "Coda", typeface: "sans-serif" },
        { name: "Coda Caption", typeface: "sans-serif" },
        { name: "Codystar", typeface: "sans-serif" },
        { name: "Combo", typeface: "sans-serif" },
        { name: "Comfortaa", typeface: "sans-serif" },
        { name: "Coming Soon", typeface: "serif" },
        { name: "Concert One", typeface: "sans-serif" },
        { name: "Condiment", typeface: "serif" },
        { name: "Content", typeface: "serif" },
        { name: "Contrail One", typeface: "sans-serif" },
        { name: "Convergence", typeface: "sans-serif" },
        { name: "Cookie", typeface: "serif" },
        { name: "Copse", typeface: "serif" },
        { name: "Corben", typeface: "serif" },
        { name: "Courgette", typeface: "serif" },
        { name: "Cousine", typeface: "sans-serif" },
        { name: "Coustard", typeface: "serif" },
        { name: "Covered By Your Grace", typeface: "serif" },
        { name: "Crafty Girls", typeface: "serif" },
        { name: "Creepster", typeface: "serif" },
        { name: "Crete Round", typeface: "serif" },
        { name: "Crimson Text", typeface: "serif" },
        { name: "Croissant One", typeface: "serif" },
        { name: "Crushed", typeface: "sans-serif" },
        { name: "Cuprum", typeface: "sans-serif" },
        { name: "Cutive", typeface: "serif" },
        { name: "Cutive Mono", typeface: "serif" },
        { name: "Damion", typeface: "serif" },
        { name: "Dancing Script", typeface: "serif" },
        { name: "Dangrek", typeface: "sans-serif" },
        { name: "Dawning of a New Day", typeface: "serif" },
        { name: "Days One", typeface: "sans-serif" },
        { name: "Dekko", typeface: "sans-serif" },
        { name: "Delius", typeface: "serif" },
        { name: "Delius Swash Caps", typeface: "serif" },
        { name: "Delius Unicase", typeface: "sans-serif" },
        { name: "Della Respira", typeface: "serif" },
        { name: "Denk One", typeface: "sans-serif" },
        { name: "Devonshire", typeface: "serif" },
        { name: "Dhurjati", typeface: "sans-serif" },
        { name: "Didact Gothic", typeface: "sans-serif" },
        { name: "Diplomata", typeface: "serif" },
        { name: "Diplomata SC", typeface: "serif" },
        { name: "Domine", typeface: "serif" },
        { name: "Donegal One", typeface: "serif" },
        { name: "Doppio One", typeface: "sans-serif" },
        { name: "Dorsa", typeface: "sans-serif" },
        { name: "Dosis", typeface: "sans-serif" },
        { name: "Dr Sugiyama", typeface: "serif" },
        { name: "Droid Sans", typeface: "sans-serif" },
        { name: "Droid Sans Mono", typeface: "sans-serif" },
        { name: "Droid Serif", typeface: "serif" },
        { name: "Duru Sans", typeface: "sans-serif" },
        { name: "Dynalight", typeface: "serif" },
        { name: "EB Garamond", typeface: "serif" },
        { name: "Eagle Lake", typeface: "serif" },
        { name: "Eater", typeface: "sans-serif" },
        { name: "Economica", typeface: "sans-serif" },
        { name: "Ek Mukta", typeface: "sans-serif" },
        { name: "Electrolize", typeface: "sans-serif" },
        { name: "Elsie", typeface: "serif" },
        { name: "Elsie Swash Caps", typeface: "serif" },
        { name: "Emblema One", typeface: "sans-serif" },
        { name: "Emilys Candy", typeface: "serif" },
        { name: "Engagement", typeface: "serif" },
        { name: "Englebert", typeface: "sans-serif" },
        { name: "Enriqueta", typeface: "serif" },
        { name: "Erica One", typeface: "sans-serif" },
        { name: "Esteban", typeface: "serif" },
        { name: "Euphoria Script", typeface: "serif" },
        { name: "Ewert", typeface: "serif" },
        { name: "Exo", typeface: "sans-serif" },
        { name: "Exo 2", typeface: "sans-serif" },
        { name: "Expletus Sans", typeface: "sans-serif" },
        { name: "Fanwood Text", typeface: "serif" },
        { name: "Fascinate", typeface: "sans-serif" },
        { name: "Fascinate Inline", typeface: "sans-serif" },
        { name: "Faster One", typeface: "sans-serif" },
        { name: "Fasthand", typeface: "serif" },
        { name: "Fauna One", typeface: "serif" },
        { name: "Federant", typeface: "serif" },
        { name: "Federo", typeface: "sans-serif" },
        { name: "Felipa", typeface: "serif" },
        { name: "Fenix", typeface: "serif" },
        { name: "Finger Paint", typeface: "serif" },
        { name: "Fira Mono", typeface: "sans-serif" },
        { name: "Fira Sans", typeface: "sans-serif" },
        { name: "Fjalla One", typeface: "sans-serif" },
        { name: "Fjord One", typeface: "serif" },
        { name: "Flamenco", typeface: "serif" },
        { name: "Flavors", typeface: "serif" },
        { name: "Fondamento", typeface: "serif" },
        { name: "Fontdiner Swanky", typeface: "serif" },
        { name: "Forum", typeface: "serif" },
        { name: "Francois One", typeface: "sans-serif" },
        { name: "Freckle Face", typeface: "serif" },
        { name: "Fredericka the Great", typeface: "serif" },
        { name: "Fredoka One", typeface: "sans-serif" },
        { name: "Freehand", typeface: "serif" },
        { name: "Fresca", typeface: "sans-serif" },
        { name: "Frijole", typeface: "sans-serif" },
        { name: "Fruktur", typeface: "serif" },
        { name: "Fugaz One", typeface: "sans-serif" },
        { name: "GFS Didot", typeface: "serif" },
        { name: "GFS Neohellenic", typeface: "sans-serif" },
        { name: "Gabriela", typeface: "serif" },
        { name: "Gafata", typeface: "sans-serif" },
        { name: "Galdeano", typeface: "sans-serif" },
        { name: "Galindo", typeface: "sans-serif" },
        { name: "Gentium Basic", typeface: "serif" },
        { name: "Gentium Book Basic", typeface: "serif" },
        { name: "Geo", typeface: "sans-serif" },
        { name: "Geostar", typeface: "serif" },
        { name: "Geostar Fill", typeface: "serif" },
        { name: "Germania One", typeface: "serif" },
        { name: "Gidugu", typeface: "sans-serif" },
        { name: "Gilda Display", typeface: "serif" },
        { name: "Give You Glory", typeface: "serif" },
        { name: "Glass Antiqua", typeface: "sans-serif" },
        { name: "Glegoo", typeface: "serif" },
        { name: "Gloria Hallelujah", typeface: "serif" },
        { name: "Goblin One", typeface: "sans-serif" },
        { name: "Gochi Hand", typeface: "serif" },
        { name: "Gorditas", typeface: "sans-serif" },
        { name: "Goudy Bookletter 1911", typeface: "serif" },
        { name: "Graduate", typeface: "serif" },
        { name: "Grand Hotel", typeface: "serif" },
        { name: "Gravitas One", typeface: "serif" },
        { name: "Great Vibes", typeface: "serif" },
        { name: "Griffy", typeface: "serif" },
        { name: "Gruppo", typeface: "sans-serif" },
        { name: "Gudea", typeface: "sans-serif" },
        { name: "Gurajada", typeface: "serif" },
        { name: "Habibi", typeface: "serif" },
        { name: "Halant", typeface: "serif" },
        { name: "Hammersmith One", typeface: "sans-serif" },
        { name: "Hanalei", typeface: "serif" },
        { name: "Hanalei Fill", typeface: "serif" },
        { name: "Handlee", typeface: "serif" },
        { name: "Hanuman", typeface: "serif" },
        { name: "Happy Monkey", typeface: "sans-serif" },
        { name: "Headland One", typeface: "serif" },
        { name: "Henny Penny", typeface: "serif" },
        { name: "Herr Von Muellerhoff", typeface: "serif" },
        { name: "Hind", typeface: "sans-serif" },
        { name: "Holtwood One SC", typeface: "serif" },
        { name: "Homemade Apple", typeface: "serif" },
        { name: "Homenaje", typeface: "sans-serif" },
        { name: "IM Fell DW Pica", typeface: "serif" },
        { name: "IM Fell DW Pica SC", typeface: "serif" },
        { name: "IM Fell Double Pica", typeface: "serif" },
        { name: "IM Fell Double Pica SC", typeface: "serif" },
        { name: "IM Fell English", typeface: "serif" },
        { name: "IM Fell English SC", typeface: "serif" },
        { name: "IM Fell French Canon", typeface: "serif" },
        { name: "IM Fell French Canon SC", typeface: "serif" },
        { name: "IM Fell Great Primer", typeface: "serif" },
        { name: "IM Fell Great Primer SC", typeface: "serif" },
        { name: "Iceberg", typeface: "sans-serif" },
        { name: "Iceland", typeface: "sans-serif" },
        { name: "Imprima", typeface: "sans-serif" },
        { name: "Inconsolata", typeface: "sans-serif" },
        { name: "Inder", typeface: "sans-serif" },
        { name: "Indie Flower", typeface: "serif" },
        { name: "Inika", typeface: "serif" },
        { name: "Irish Grover", typeface: "serif" },
        { name: "Istok Web", typeface: "sans-serif" },
        { name: "Italiana", typeface: "serif" },
        { name: "Italianno", typeface: "serif" },
        { name: "Jacques Francois", typeface: "serif" },
        { name: "Jacques Francois Shadow", typeface: "serif" },
        { name: "Jaldi", typeface: "sans-serif" },
        { name: "Jim Nightshade", typeface: "serif" },
        { name: "Jockey One", typeface: "sans-serif" },
        { name: "Jolly Lodger", typeface: "serif" },
        { name: "Josefin Sans", typeface: "sans-serif" },
        { name: "Josefin Slab", typeface: "serif" },
        { name: "Joti One", typeface: "sans-serif" },
        { name: "Judson", typeface: "serif" },
        { name: "Julee", typeface: "serif" },
        { name: "Julius Sans One", typeface: "sans-serif" },
        { name: "Junge", typeface: "serif" },
        { name: "Jura", typeface: "sans-serif" },
        { name: "Just Another Hand", typeface: "serif" },
        { name: "Just Me Again Down Here", typeface: "serif" },
        { name: "Kalam", typeface: "serif" },
        { name: "Kameron", typeface: "serif" },
        { name: "Kantumruy", typeface: "sans-serif" },
        { name: "Karla", typeface: "sans-serif" },
        { name: "Karma", typeface: "serif" },
        { name: "Kaushan Script", typeface: "serif" },
        { name: "Kavoon", typeface: "serif" },
        { name: "Kdam Thmor", typeface: "sans-serif" },
        { name: "Keania One", typeface: "serif" },
        { name: "Kelly Slab", typeface: "serif" },
        { name: "Kenia", typeface: "serif" },
        { name: "Khand", typeface: "sans-serif" },
        { name: "Khmer", typeface: "sans-serif" },
        { name: "Khula", typeface: "sans-serif" },
        { name: "Kite One", typeface: "sans-serif" },
        { name: "Knewave", typeface: "serif" },
        { name: "Kotta One", typeface: "serif" },
        { name: "Koulen", typeface: "serif" },
        { name: "Kranky", typeface: "serif" },
        { name: "Kreon", typeface: "serif" },
        { name: "Kristi", typeface: "serif" },
        { name: "Krona One", typeface: "sans-serif" },
        { name: "La Belle Aurore", typeface: "serif" },
        { name: "Laila", typeface: "serif" },
        { name: "Lakki Reddy", typeface: "serif" },
        { name: "Lancelot", typeface: "serif" },
        { name: "Lateef", typeface: "serif" },
        { name: "Lato", typeface: "sans-serif" },
        { name: "League Script", typeface: "serif" },
        { name: "Leckerli One", typeface: "serif" },
        { name: "Ledger", typeface: "serif" },
        { name: "Lekton", typeface: "sans-serif" },
        { name: "Lemon", typeface: "serif" },
        { name: "Libre Baskerville", typeface: "serif" },
        { name: "Life Savers", typeface: "sans-serif" },
        { name: "Lilita One", typeface: "serif" },
        { name: "Lily Script One", typeface: "serif" },
        { name: "Limelight", typeface: "serif" },
        { name: "Linden Hill", typeface: "serif" },
        { name: "Lobster", typeface: "serif" },
        { name: "Lobster Two", typeface: "serif" },
        { name: "Londrina Outline", typeface: "serif" },
        { name: "Londrina Shadow", typeface: "serif" },
        { name: "Londrina Sketch", typeface: "serif" },
        { name: "Londrina Solid", typeface: "serif" },
        { name: "Lora", typeface: "serif" },
        { name: "Love Ya Like A Sister", typeface: "sans-serif" },
        { name: "Loved by the King", typeface: "serif" },
        { name: "Lovers Quarrel", typeface: "serif" },
        { name: "Luckiest Guy", typeface: "sans-serif" },
        { name: "Lusitana", typeface: "serif" },
        { name: "Lustria", typeface: "serif" },
        { name: "Macondo", typeface: "serif" },
        { name: "Macondo Swash Caps", typeface: "serif" },
        { name: "Magra", typeface: "sans-serif" },
        { name: "Maiden Orange", typeface: "serif" },
        { name: "Mako", typeface: "sans-serif" },
        { name: "Mallanna", typeface: "sans-serif" },
        { name: "Mandali", typeface: "sans-serif" },
        { name: "Marcellus", typeface: "serif" },
        { name: "Marcellus SC", typeface: "serif" },
        { name: "Marck Script", typeface: "serif" },
        { name: "Margarine", typeface: "serif" },
        { name: "Marko One", typeface: "serif" },
        { name: "Marmelad", typeface: "sans-serif" },
        { name: "Martel", typeface: "serif" },
        { name: "Martel Sans", typeface: "sans-serif" },
        { name: "Marvel", typeface: "sans-serif" },
        { name: "Mate", typeface: "serif" },
        { name: "Mate SC", typeface: "serif" },
        { name: "Maven Pro", typeface: "sans-serif" },
        { name: "McLaren", typeface: "serif" },
        { name: "Meddon", typeface: "serif" },
        { name: "MedievalSharp", typeface: "serif" },
        { name: "Medula One", typeface: "serif" },
        { name: "Megrim", typeface: "sans-serif" },
        { name: "Meie Script", typeface: "serif" },
        { name: "Merienda", typeface: "serif" },
        { name: "Merienda One", typeface: "serif" },
        { name: "Merriweather", typeface: "serif" },
        { name: "Merriweather Sans", typeface: "sans-serif" },
        { name: "Metal", typeface: "serif" },
        { name: "Metal Mania", typeface: "serif" },
        { name: "Metamorphous", typeface: "serif" },
        { name: "Metrophobic", typeface: "sans-serif" },
        { name: "Michroma", typeface: "sans-serif" },
        { name: "Milonga", typeface: "serif" },
        { name: "Miltonian", typeface: "serif" },
        { name: "Miltonian Tattoo", typeface: "serif" },
        { name: "Miniver", typeface: "serif" },
        { name: "Miss Fajardose", typeface: "serif" },
        { name: "Modak", typeface: "serif" },
        { name: "Modern Antiqua", typeface: "serif" },
        { name: "Molengo", typeface: "sans-serif" },
        { name: "Molle", typeface: "serif" },
        { name: "Monda", typeface: "sans-serif" },
        { name: "Monofett", typeface: "serif" },
        { name: "Monoton", typeface: "serif" },
        { name: "Monsieur La Doulaise", typeface: "serif" },
        { name: "Montaga", typeface: "serif" },
        { name: "Montez", typeface: "serif" },
        { name: "Montserrat", typeface: "sans-serif" },
        { name: "Montserrat Alternates", typeface: "sans-serif" },
        { name: "Montserrat Subrayada", typeface: "sans-serif" },
        { name: "Moul", typeface: "serif" },
        { name: "Moulpali", typeface: "serif" },
        { name: "Mountains of Christmas", typeface: "serif" },
        { name: "Mouse Memoirs", typeface: "sans-serif" },
        { name: "Mr Bedfort", typeface: "serif" },
        { name: "Mr Dafoe", typeface: "serif" },
        { name: "Mr De Haviland", typeface: "serif" },
        { name: "Mrs Saint Delafield", typeface: "serif" },
        { name: "Mrs Sheppards", typeface: "serif" },
        { name: "Muli", typeface: "sans-serif" },
        { name: "Mystery Quest", typeface: "serif" },
        { name: "NTR", typeface: "sans-serif" },
        { name: "Neucha", typeface: "sans-serif" },
        { name: "Neuton", typeface: "serif" },
        { name: "New Rocker", typeface: "serif" },
        { name: "News Cycle", typeface: "sans-serif" },
        { name: "Niconne", typeface: "serif" },
        { name: "Nixie One", typeface: "serif" },
        { name: "Nobile", typeface: "sans-serif" },
        { name: "Nokora", typeface: "serif" },
        { name: "Norican", typeface: "serif" },
        { name: "Nosifer", typeface: "serif" },
        { name: "Nothing You Could Do", typeface: "serif" },
        { name: "Noticia Text", typeface: "serif" },
        { name: "Noto Sans", typeface: "sans-serif" },
        { name: "Noto Serif", typeface: "serif" },
        { name: "Nova Cut", typeface: "serif" },
        { name: "Nova Flat", typeface: "serif" },
        { name: "Nova Mono", typeface: "sans-serif" },
        { name: "Nova Oval", typeface: "serif" },
        { name: "Nova Round", typeface: "serif" },
        { name: "Nova Script", typeface: "serif" },
        { name: "Nova Slim", typeface: "serif" },
        { name: "Nova Square", typeface: "serif" },
        { name: "Numans", typeface: "sans-serif" },
        { name: "Nunito", typeface: "sans-serif" },
        { name: "Odor Mean Chey", typeface: "serif" },
        { name: "Offside", typeface: "sans-serif" },
        { name: "Old Standard TT", typeface: "serif" },
        { name: "Oldenburg", typeface: "serif" },
        { name: "Oleo Script", typeface: "serif" },
        { name: "Oleo Script Swash Caps", typeface: "serif" },
        { name: "Open Sans", typeface: "sans-serif" },
        { name: "Open Sans Condensed", typeface: "sans-serif" },
        { name: "Oranienbaum", typeface: "serif" },
        { name: "Orbitron", typeface: "sans-serif" },
        { name: "Oregano", typeface: "serif" },
        { name: "Orienta", typeface: "sans-serif" },
        { name: "Original Surfer", typeface: "serif" },
        { name: "Oswald", typeface: "sans-serif" },
        { name: "Over the Rainbow", typeface: "serif" },
        { name: "Overlock", typeface: "serif" },
        { name: "Overlock SC", typeface: "serif" },
        { name: "Ovo", typeface: "serif" },
        { name: "Oxygen", typeface: "sans-serif" },
        { name: "Oxygen Mono", typeface: "sans-serif" },
        { name: "PT Mono", typeface: "sans-serif" },
        { name: "PT Sans", typeface: "sans-serif" },
        { name: "PT Sans Caption", typeface: "sans-serif" },
        { name: "PT Sans Narrow", typeface: "sans-serif" },
        { name: "PT Serif", typeface: "serif" },
        { name: "PT Serif Caption", typeface: "serif" },
        { name: "Pacifico", typeface: "serif" },
        { name: "Palanquin", typeface: "sans-serif" },
        { name: "Palanquin Dark", typeface: "sans-serif" },
        { name: "Paprika", typeface: "serif" },
        { name: "Parisienne", typeface: "serif" },
        { name: "Passero One", typeface: "serif" },
        { name: "Passion One", typeface: "serif" },
        { name: "Pathway Gothic One", typeface: "sans-serif" },
        { name: "Patrick Hand", typeface: "serif" },
        { name: "Patrick Hand SC", typeface: "serif" },
        { name: "Patua One", typeface: "serif" },
        { name: "Paytone One", typeface: "sans-serif" },
        { name: "Peddana", typeface: "serif" },
        { name: "Peralta", typeface: "serif" },
        { name: "Permanent Marker", typeface: "serif" },
        { name: "Petit Formal Script", typeface: "serif" },
        { name: "Petrona", typeface: "serif" },
        { name: "Philosopher", typeface: "sans-serif" },
        { name: "Piedra", typeface: "serif" },
        { name: "Pinyon Script", typeface: "serif" },
        { name: "Pirata One", typeface: "serif" },
        { name: "Plaster", typeface: "serif" },
        { name: "Play", typeface: "sans-serif" },
        { name: "Playball", typeface: "serif" },
        { name: "Playfair Display", typeface: "serif" },
        { name: "Playfair Display SC", typeface: "serif" },
        { name: "Podkova", typeface: "serif" },
        { name: "Poiret One", typeface: "serif" },
        { name: "Poller One", typeface: "serif" },
        { name: "Poly", typeface: "serif" },
        { name: "Pompiere", typeface: "serif" },
        { name: "Pontano Sans", typeface: "sans-serif" },
        { name: "Port Lligat Sans", typeface: "sans-serif" },
        { name: "Port Lligat Slab", typeface: "serif" },
        { name: "Pragati Narrow", typeface: "sans-serif" },
        { name: "Prata", typeface: "serif" },
        { name: "Preahvihear", typeface: "serif" },
        { name: "Press Start 2P", typeface: "serif" },
        { name: "Princess Sofia", typeface: "serif" },
        { name: "Prociono", typeface: "serif" },
        { name: "Prosto One", typeface: "sans-serif" },
        { name: "Puritan", typeface: "sans-serif" },
        { name: "Purple Purse", typeface: "serif" },
        { name: "Quando", typeface: "serif" },
        { name: "Quantico", typeface: "sans-serif" },
        { name: "Quattrocento", typeface: "serif" },
        { name: "Quattrocento Sans", typeface: "sans-serif" },
        { name: "Questrial", typeface: "sans-serif" },
        { name: "Quicksand", typeface: "sans-serif" },
        { name: "Quintessential", typeface: "serif" },
        { name: "Qwigley", typeface: "serif" },
        { name: "Racing Sans One", typeface: "sans-serif" },
        { name: "Radley", typeface: "serif" },
        { name: "Rajdhani", typeface: "sans-serif" },
        { name: "Raleway", typeface: "sans-serif" },
        { name: "Raleway Dots", typeface: "sans-serif" },
        { name: "Ramabhadra", typeface: "sans-serif" },
        { name: "Ramaraja", typeface: "serif" },
        { name: "Rambla", typeface: "sans-serif" },
        { name: "Rammetto One", typeface: "serif" },
        { name: "Ranchers", typeface: "serif" },
        { name: "Rancho", typeface: "serif" },
        { name: "Ranga", typeface: "serif" },
        { name: "Rationale", typeface: "sans-serif" },
        { name: "Ravi Prakash", typeface: "serif" },
        { name: "Redressed", typeface: "serif" },
        { name: "Reenie Beanie", typeface: "serif" },
        { name: "Revalia", typeface: "serif" },
        { name: "Ribeye", typeface: "serif" },
        { name: "Ribeye Marrow", typeface: "serif" },
        { name: "Righteous", typeface: "serif" },
        { name: "Risque", typeface: "serif" },
        { name: "Roboto", typeface: "sans-serif" },
        { name: "Roboto Condensed", typeface: "sans-serif" },
        { name: "Roboto Slab", typeface: "serif" },
        { name: "Rochester", typeface: "serif" },
        { name: "Rock Salt", typeface: "serif" },
        { name: "Rokkitt", typeface: "serif" },
        { name: "Romanesco", typeface: "serif" },
        { name: "Ropa Sans", typeface: "sans-serif" },
        { name: "Rosario", typeface: "serif" },
        { name: "Rosarivo", typeface: "serif" },
        { name: "Rouge Script", typeface: "serif" },
        { name: "Rozha One", typeface: "serif" },
        { name: "Rubik Mono One", typeface: "sans-serif" },
        { name: "Rubik One", typeface: "sans-serif" },
        { name: "Ruda", typeface: "sans-serif" },
        { name: "Rufina", typeface: "serif" },
        { name: "Ruge Boogie", typeface: "serif" },
        { name: "Ruluko", typeface: "sans-serif" },
        { name: "Rum Raisin", typeface: "sans-serif" },
        { name: "Ruslan Display", typeface: "serif" },
        { name: "Russo One", typeface: "sans-serif" },
        { name: "Ruthie", typeface: "serif" },
        { name: "Rye", typeface: "serif" },
        { name: "Sacramento", typeface: "serif" },
        { name: "Sail", typeface: "serif" },
        { name: "Salsa", typeface: "serif" },
        { name: "Sanchez", typeface: "serif" },
        { name: "Sancreek", typeface: "serif" },
        { name: "Sansita One", typeface: "serif" },
        { name: "Sarina", typeface: "serif" },
        { name: "Sarpanch", typeface: "sans-serif" },
        { name: "Satisfy", typeface: "serif" },
        { name: "Scada", typeface: "sans-serif" },
        { name: "Scheherazade", typeface: "serif" },
        { name: "Schoolbell", typeface: "serif" },
        { name: "Seaweed Script", typeface: "serif" },
        { name: "Sevillana", typeface: "serif" },
        { name: "Seymour One", typeface: "sans-serif" },
        { name: "Shadows Into Light", typeface: "serif" },
        { name: "Shadows Into Light Two", typeface: "serif" },
        { name: "Shanti", typeface: "sans-serif" },
        { name: "Share", typeface: "serif" },
        { name: "Share Tech", typeface: "sans-serif" },
        { name: "Share Tech Mono", typeface: "sans-serif" },
        { name: "Shojumaru", typeface: "serif" },
        { name: "Short Stack", typeface: "serif" },
        { name: "Siemreap", typeface: "serif" },
        { name: "Sigmar One", typeface: "serif" },
        { name: "Signika", typeface: "sans-serif" },
        { name: "Signika Negative", typeface: "sans-serif" },
        { name: "Simonetta", typeface: "serif" },
        { name: "Sintony", typeface: "sans-serif" },
        { name: "Sirin Stencil", typeface: "serif" },
        { name: "Six Caps", typeface: "sans-serif" },
        { name: "Skranji", typeface: "serif" },
        { name: "Slabo 13px", typeface: "serif" },
        { name: "Slabo 27px", typeface: "serif" },
        { name: "Slackey", typeface: "serif" },
        { name: "Smokum", typeface: "serif" },
        { name: "Smythe", typeface: "serif" },
        { name: "Sniglet", typeface: "sans-serif" },
        { name: "Snippet", typeface: "sans-serif" },
        { name: "Snowburst One", typeface: "serif" },
        { name: "Sofadi One", typeface: "serif" },
        { name: "Sofia", typeface: "serif" },
        { name: "Sonsie One", typeface: "serif" },
        { name: "Sorts Mill Goudy", typeface: "serif" },
        { name: "Source Code Pro", typeface: "sans-serif" },
        { name: "Source Sans Pro", typeface: "sans-serif" },
        { name: "Source Serif Pro", typeface: "serif" },
        { name: "Special Elite", typeface: "serif" },
        { name: "Spicy Rice", typeface: "serif" },
        { name: "Spinnaker", typeface: "sans-serif" },
        { name: "Spirax", typeface: "serif" },
        { name: "Squada One", typeface: "sans-serif" },
        { name: "Sree Krushnadevaraya", typeface: "serif" },
        { name: "Stalemate", typeface: "serif" },
        { name: "Stalinist One", typeface: "serif" },
        { name: "Stardos Stencil", typeface: "serif" },
        { name: "Stint Ultra Condensed", typeface: "sans-serif" },
        { name: "Stint Ultra Expanded", typeface: "sans-serif" },
        { name: "Stoke", typeface: "serif" },
        { name: "Strait", typeface: "sans-serif" },
        { name: "Sue Ellen Francisco", typeface: "serif" },
        { name: "Sunshiney", typeface: "serif" },
        { name: "Supermercado One", typeface: "sans-serif" },
        { name: "Suranna", typeface: "serif" },
        { name: "Suravaram", typeface: "serif" },
        { name: "Suwannaphum", typeface: "serif" },
        { name: "Swanky and Moo Moo", typeface: "serif" },
        { name: "Syncopate", typeface: "sans-serif" },
        { name: "Tangerine", typeface: "serif" },
        { name: "Taprom", typeface: "serif" },
        { name: "Tauri", typeface: "sans-serif" },
        { name: "Teko", typeface: "sans-serif" },
        { name: "Telex", typeface: "sans-serif" },
        { name: "Tenali Ramakrishna", typeface: "serif" },
        { name: "Tenor Sans", typeface: "sans-serif" },
        { name: "Text Me One", typeface: "sans-serif" },
        { name: "The Girl Next Door", typeface: "serif" },
        { name: "Tienne", typeface: "serif" },
        { name: "Timmana", typeface: "sans-serif" },
        { name: "Tinos", typeface: "serif" },
        { name: "Titan One", typeface: "serif" },
        { name: "Titillium Web", typeface: "sans-serif" },
        { name: "Trade Winds", typeface: "serif" },
        { name: "Trocchi", typeface: "serif" },
        { name: "Trochut", typeface: "serif" },
        { name: "Trykker", typeface: "serif" },
        { name: "Tulpen One", typeface: "serif" },
        { name: "Ubuntu", typeface: "sans-serif" },
        { name: "Ubuntu Condensed", typeface: "sans-serif" },
        { name: "Ubuntu Mono", typeface: "sans-serif" },
        { name: "Ultra", typeface: "serif" },
        { name: "Uncial Antiqua", typeface: "serif" },
        { name: "Underdog", typeface: "serif" },
        { name: "Unica One", typeface: "serif" },
        { name: "UnifrakturCook", typeface: "serif" },
        { name: "UnifrakturMaguntia", typeface: "serif" },
        { name: "Unkempt", typeface: "serif" },
        { name: "Unlock", typeface: "sans-serif" },
        { name: "Unna", typeface: "serif" },
        { name: "VT323", typeface: "sans-serif" },
        { name: "Vampiro One", typeface: "serif" },
        { name: "Varela", typeface: "sans-serif" },
        { name: "Varela Round", typeface: "sans-serif" },
        { name: "Vast Shadow", typeface: "serif" },
        { name: "Vesper Libre", typeface: "serif" },
        { name: "Vibur", typeface: "serif" },
        { name: "Vidaloka", typeface: "serif" },
        { name: "Viga", typeface: "sans-serif" },
        { name: "Voces", typeface: "sans-serif" },
        { name: "Volkhov", typeface: "serif" },
        { name: "Vollkorn", typeface: "serif" },
        { name: "Voltaire", typeface: "sans-serif" },
        { name: "Waiting for the Sunrise", typeface: "serif" },
        { name: "Wallpoet", typeface: "serif" },
        { name: "Walter Turncoat", typeface: "serif" },
        { name: "Warnes", typeface: "sans-serif" },
        { name: "Wellfleet", typeface: "serif" },
        { name: "Wendy One", typeface: "sans-serif" },
        { name: "Wire One", typeface: "sans-serif" },
        { name: "Yanone Kaffeesatz", typeface: "sans-serif" },
        { name: "Yellowtail", typeface: "serif" },
        { name: "Yeseva One", typeface: "serif" },
        { name: "Yesteryear", typeface: "serif" },
        { name: "Zeyada", typeface: "serif" },
      ],
    });
  }

  const weights = [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ];

  const getFontOptions = () => {
    return allFonts.reduce((fontList, fontGroup) => {
      const fonts = fontGroup.fonts.map((font) => {
        return {
          value: font.name,
          label: font.name,
        };
      });
      const group = {
        label: fontGroup.label,
        options: fonts,
      };
      return [...fontList, group];
    }, []);
  };

  const updateFontFamily = (value) => {
    let type;
    let typeface;

    for (let i = 0; i < allFonts.length; i++) {
      for (let e = 0; e < allFonts[i].fonts.length; e++) {
        if (value === allFonts[i].fonts[e].name) {
          type = allFonts[i].id;
          typeface = allFonts[i].fonts[e].typeface;
          break;
        }
      }
    }

    handleUpdateFont({
      fontType: type,
      fontFamily: value,
      fontTypeface: typeface,
    });
  };

  return (
    <BaseField {...props} type="typography">
      {options.includes("fontFamily") && (
        <SelectField
          id="fontFamily"
          name={__("Font Family", "ditty-news-ticker")}
          placeholder={__("Select Font Family", "ditty-news-ticker")}
          options={getFontOptions()}
          value={value.fontFamily ? value.fontFamily : false}
          onChange={(val) => updateFontFamily(val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("fontWeight") && (
        <SelectField
          id="fontWeight"
          name={__("Font Weight", "ditty-news-ticker")}
          placeholder=" "
          options={weights}
          value={value.fontWeight ? value.fontWeight : false}
          onChange={(val) => handleUpdateFont("fontWeight", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("fontSize") && (
        <UnitField
          id="fontSize"
          name={__("Font Size", "ditty-news-ticker")}
          value={value.fontSize ? value.fontSize : false}
          onChange={(val) => handleUpdateFont("fontSize", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("lineHeight") && (
        <UnitField
          id="lineHeight"
          name={__("Line Height", "ditty-news-ticker")}
          value={value.lineHeight ? value.lineHeight : false}
          onChange={(val) => handleUpdateFont("lineHeight", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("letterSpacing") && (
        <UnitField
          id="letterSpacing"
          name={__("Letter Spacing", "ditty-news-ticker")}
          value={value.letterSpacing ? value.letterSpacing : false}
          onChange={(val) => handleUpdateFont("letterSpacing", val)}
          className="ditty-field--typography__field"
        />
      )}
    </BaseField>
  );
};

export default TypographyField;
