import { __ } from "@wordpress/i18n";
import BaseField from "./BaseField";
import SelectField from "./SelectField";
import UnitField from "./UnitField";

const TypographyField = (props) => {
  const {
    value = {},
    options = [
      "fontFamily",
      "fontWeight",
      "fontSize",
      "lineHeight",
      "letterSpacing",
    ],
    onChange,
  } = props;

  const handleUpdateFont = (key, val) => {
    let updatedValue = { ...value };
    if ("object" === typeof key) {
      updatedValue = { ...value, ...key };
    } else {
      updatedValue[key] = val;
    }
    onChange(updatedValue);
  };

  const allFonts = [
    {
      id: "standard",
      label: __("Standard Fonts", "ditty-news-ticker"),
      fonts: [
        { name: "Arial" },
        { name: "Arial Black" },
        { name: "Courier New" },
        { name: "Georgia" },
        { name: "Times New Roman" },
        { name: "Trebuchet MS" },
        { name: "Verdana" },
        { name: "Impact" },
        { name: "Lucida Console" },
        { name: "Tahoma" },
        { name: "Lucida Sans Unicode" },
        { name: "Palatino Linotype" },
        { name: "Comic Sans MS" },
      ],
    },
    {
      id: "google",
      label: __("Google Fonts", "ditty-news-ticker"),
      fonts: [
        { name: "ABeeZee" },
        { name: "Abel" },
        { name: "Abril Fatface" },
        { name: "Aclonica" },
        { name: "Acme" },
        { name: "Actor" },
        { name: "Adamina" },
        { name: "Advent Pro" },
        { name: "Aguafina Script" },
        { name: "Akronim" },
        { name: "Aladin" },
        { name: "Aldrich" },
        { name: "Alef" },
        { name: "Alegreya" },
        { name: "Alegreya SC" },
        { name: "Alegreya Sans" },
        { name: "Alegreya Sans SC" },
        { name: "Alex Brush" },
        { name: "Alfa Slab One" },
        { name: "Alice" },
        { name: "Alike" },
        { name: "Alike Angular" },
        { name: "Allan" },
        { name: "Allerta" },
        { name: "Allerta Stencil" },
        { name: "Allura" },
        { name: "Almendra" },
        { name: "Almendra Display" },
        { name: "Almendra SC" },
        { name: "Amarante" },
        { name: "Amaranth" },
        { name: "Amatic SC" },
        { name: "Amethysta" },
        { name: "Amiri" },
        { name: "Anaheim" },
        { name: "Andada" },
        { name: "Andika" },
        { name: "Angkor" },
        { name: "Annie Use Your Telescope" },
        { name: "Anonymous Pro" },
        { name: "Antic" },
        { name: "Antic Didone" },
        { name: "Antic Slab" },
        { name: "Anton" },
        { name: "Arapey" },
        { name: "Arbutus" },
        { name: "Arbutus Slab" },
        { name: "Architects Daughter" },
        { name: "Archivo Black" },
        { name: "Archivo Narrow" },
        { name: "Arimo" },
        { name: "Arizonia" },
        { name: "Armata" },
        { name: "Artifika" },
        { name: "Arvo" },
        { name: "Asap" },
        { name: "Asset" },
        { name: "Astloch" },
        { name: "Asul" },
        { name: "Atomic Age" },
        { name: "Aubrey" },
        { name: "Audiowide" },
        { name: "Autour One" },
        { name: "Average" },
        { name: "Average Sans" },
        { name: "Averia Gruesa Libre" },
        { name: "Averia Libre" },
        { name: "Averia Sans Libre" },
        { name: "Averia Serif Libre" },
        { name: "Bad Script" },
        { name: "Balthazar" },
        { name: "Bangers" },
        { name: "Basic" },
        { name: "Battambang" },
        { name: "Baumans" },
        { name: "Bayon" },
        { name: "Belgrano" },
        { name: "Belleza" },
        { name: "BenchNine" },
        { name: "Bentham" },
        { name: "Berkshire Swash" },
        { name: "Bevan" },
        { name: "Bigelow Rules" },
        { name: "Bigshot One" },
        { name: "Bilbo" },
        { name: "Bilbo Swash Caps" },
        { name: "Biryani" },
        { name: "Bitter" },
        { name: "Black Ops One" },
        { name: "Bokor" },
        { name: "Bonbon" },
        { name: "Boogaloo" },
        { name: "Bowlby One" },
        { name: "Bowlby One SC" },
        { name: "Brawler" },
        { name: "Bree Serif" },
        { name: "Bubblegum Sans" },
        { name: "Bubbler One" },
        { name: "Buda" },
        { name: "Buenard" },
        { name: "Butcherman" },
        { name: "Butterfly Kids" },
        { name: "Cabin" },
        { name: "Cabin Condensed" },
        { name: "Cabin Sketch" },
        { name: "Caesar Dressing" },
        { name: "Cagliostro" },
        { name: "Calligraffitti" },
        { name: "Cambay" },
        { name: "Cambo" },
        { name: "Candal" },
        { name: "Cantarell" },
        { name: "Cantata One" },
        { name: "Cantora One" },
        { name: "Capriola" },
        { name: "Cardo" },
        { name: "Carme" },
        { name: "Carrois Gothic" },
        { name: "Carrois Gothic SC" },
        { name: "Carter One" },
        { name: "Caudex" },
        { name: "Cedarville Cursive" },
        { name: "Ceviche One" },
        { name: "Changa One" },
        { name: "Chango" },
        { name: "Chau Philomene One" },
        { name: "Chela One" },
        { name: "Chelsea Market" },
        { name: "Chenla" },
        { name: "Cherry Cream Soda" },
        { name: "Cherry Swash" },
        { name: "Chewy" },
        { name: "Chicle" },
        { name: "Chivo" },
        { name: "Cinzel" },
        { name: "Cinzel Decorative" },
        { name: "Clicker Script" },
        { name: "Coda" },
        { name: "Coda Caption" },
        { name: "Codystar" },
        { name: "Combo" },
        { name: "Comfortaa" },
        { name: "Coming Soon" },
        { name: "Concert One" },
        { name: "Condiment" },
        { name: "Content" },
        { name: "Contrail One" },
        { name: "Convergence" },
        { name: "Cookie" },
        { name: "Copse" },
        { name: "Corben" },
        { name: "Courgette" },
        { name: "Cousine" },
        { name: "Coustard" },
        { name: "Covered By Your Grace" },
        { name: "Crafty Girls" },
        { name: "Creepster" },
        { name: "Crete Round" },
        { name: "Crimson Text" },
        { name: "Croissant One" },
        { name: "Crushed" },
        { name: "Cuprum" },
        { name: "Cutive" },
        { name: "Cutive Mono" },
        { name: "Damion" },
        { name: "Dancing Script" },
        { name: "Dangrek" },
        { name: "Dawning of a New Day" },
        { name: "Days One" },
        { name: "Dekko" },
        { name: "Delius" },
        { name: "Delius Swash Caps" },
        { name: "Delius Unicase" },
        { name: "Della Respira" },
        { name: "Denk One" },
        { name: "Devonshire" },
        { name: "Dhurjati" },
        { name: "Didact Gothic" },
        { name: "Diplomata" },
        { name: "Diplomata SC" },
        { name: "Domine" },
        { name: "Donegal One" },
        { name: "Doppio One" },
        { name: "Dorsa" },
        { name: "Dosis" },
        { name: "Dr Sugiyama" },
        { name: "Droid Sans" },
        { name: "Droid Sans Mono" },
        { name: "Droid Serif" },
        { name: "Duru Sans" },
        { name: "Dynalight" },
        { name: "EB Garamond" },
        { name: "Eagle Lake" },
        { name: "Eater" },
        { name: "Economica" },
        { name: "Ek Mukta" },
        { name: "Electrolize" },
        { name: "Elsie" },
        { name: "Elsie Swash Caps" },
        { name: "Emblema One" },
        { name: "Emilys Candy" },
        { name: "Engagement" },
        { name: "Englebert" },
        { name: "Enriqueta" },
        { name: "Erica One" },
        { name: "Esteban" },
        { name: "Euphoria Script" },
        { name: "Ewert" },
        { name: "Exo" },
        { name: "Exo 2" },
        { name: "Expletus Sans" },
        { name: "Fanwood Text" },
        { name: "Fascinate" },
        { name: "Fascinate Inline" },
        { name: "Faster One" },
        { name: "Fasthand" },
        { name: "Fauna One" },
        { name: "Federant" },
        { name: "Federo" },
        { name: "Felipa" },
        { name: "Fenix" },
        { name: "Finger Paint" },
        { name: "Fira Mono" },
        { name: "Fira Sans" },
        { name: "Fjalla One" },
        { name: "Fjord One" },
        { name: "Flamenco" },
        { name: "Flavors" },
        { name: "Fondamento" },
        { name: "Fontdiner Swanky" },
        { name: "Forum" },
        { name: "Francois One" },
        { name: "Freckle Face" },
        { name: "Fredericka the Great" },
        { name: "Fredoka One" },
        { name: "Freehand" },
        { name: "Fresca" },
        { name: "Frijole" },
        { name: "Fruktur" },
        { name: "Fugaz One" },
        { name: "GFS Didot" },
        { name: "GFS Neohellenic" },
        { name: "Gabriela" },
        { name: "Gafata" },
        { name: "Galdeano" },
        { name: "Galindo" },
        { name: "Gentium Basic" },
        { name: "Gentium Book Basic" },
        { name: "Geo" },
        { name: "Geostar" },
        { name: "Geostar Fill" },
        { name: "Germania One" },
        { name: "Gidugu" },
        { name: "Gilda Display" },
        { name: "Give You Glory" },
        { name: "Glass Antiqua" },
        { name: "Glegoo" },
        { name: "Gloria Hallelujah" },
        { name: "Goblin One" },
        { name: "Gochi Hand" },
        { name: "Gorditas" },
        { name: "Goudy Bookletter 1911" },
        { name: "Graduate" },
        { name: "Grand Hotel" },
        { name: "Gravitas One" },
        { name: "Great Vibes" },
        { name: "Griffy" },
        { name: "Gruppo" },
        { name: "Gudea" },
        { name: "Gurajada" },
        { name: "Habibi" },
        { name: "Halant" },
        { name: "Hammersmith One" },
        { name: "Hanalei" },
        { name: "Hanalei Fill" },
        { name: "Handlee" },
        { name: "Hanuman" },
        { name: "Happy Monkey" },
        { name: "Headland One" },
        { name: "Henny Penny" },
        { name: "Herr Von Muellerhoff" },
        { name: "Hind" },
        { name: "Holtwood One SC" },
        { name: "Homemade Apple" },
        { name: "Homenaje" },
        { name: "IM Fell DW Pica" },
        { name: "IM Fell DW Pica SC" },
        { name: "IM Fell Double Pica" },
        { name: "IM Fell Double Pica SC" },
        { name: "IM Fell English" },
        { name: "IM Fell English SC" },
        { name: "IM Fell French Canon" },
        { name: "IM Fell French Canon SC" },
        { name: "IM Fell Great Primer" },
        { name: "IM Fell Great Primer SC" },
        { name: "Iceberg" },
        { name: "Iceland" },
        { name: "Imprima" },
        { name: "Inconsolata" },
        { name: "Inder" },
        { name: "Indie Flower" },
        { name: "Inika" },
        { name: "Irish Grover" },
        { name: "Istok Web" },
        { name: "Italiana" },
        { name: "Italianno" },
        { name: "Jacques Francois" },
        { name: "Jacques Francois Shadow" },
        { name: "Jaldi" },
        { name: "Jim Nightshade" },
        { name: "Jockey One" },
        { name: "Jolly Lodger" },
        { name: "Josefin Sans" },
        { name: "Josefin Slab" },
        { name: "Joti One" },
        { name: "Judson" },
        { name: "Julee" },
        { name: "Julius Sans One" },
        { name: "Junge" },
        { name: "Jura" },
        { name: "Just Another Hand" },
        { name: "Just Me Again Down Here" },
        { name: "Kalam" },
        { name: "Kameron" },
        { name: "Kantumruy" },
        { name: "Karla" },
        { name: "Karma" },
        { name: "Kaushan Script" },
        { name: "Kavoon" },
        { name: "Kdam Thmor" },
        { name: "Keania One" },
        { name: "Kelly Slab" },
        { name: "Kenia" },
        { name: "Khand" },
        { name: "Khmer" },
        { name: "Khula" },
        { name: "Kite One" },
        { name: "Knewave" },
        { name: "Kotta One" },
        { name: "Koulen" },
        { name: "Kranky" },
        { name: "Kreon" },
        { name: "Kristi" },
        { name: "Krona One" },
        { name: "La Belle Aurore" },
        { name: "Laila" },
        { name: "Lakki Reddy" },
        { name: "Lancelot" },
        { name: "Lateef" },
        { name: "Lato" },
        { name: "League Script" },
        { name: "Leckerli One" },
        { name: "Ledger" },
        { name: "Lekton" },
        { name: "Lemon" },
        { name: "Libre Baskerville" },
        { name: "Life Savers" },
        { name: "Lilita One" },
        { name: "Lily Script One" },
        { name: "Limelight" },
        { name: "Linden Hill" },
        { name: "Lobster" },
        { name: "Lobster Two" },
        { name: "Londrina Outline" },
        { name: "Londrina Shadow" },
        { name: "Londrina Sketch" },
        { name: "Londrina Solid" },
        { name: "Lora" },
        { name: "Love Ya Like A Sister" },
        { name: "Loved by the King" },
        { name: "Lovers Quarrel" },
        { name: "Luckiest Guy" },
        { name: "Lusitana" },
        { name: "Lustria" },
        { name: "Macondo" },
        { name: "Macondo Swash Caps" },
        { name: "Magra" },
        { name: "Maiden Orange" },
        { name: "Mako" },
        { name: "Mallanna" },
        { name: "Mandali" },
        { name: "Marcellus" },
        { name: "Marcellus SC" },
        { name: "Marck Script" },
        { name: "Margarine" },
        { name: "Marko One" },
        { name: "Marmelad" },
        { name: "Martel" },
        { name: "Martel Sans" },
        { name: "Marvel" },
        { name: "Mate" },
        { name: "Mate SC" },
        { name: "Maven Pro" },
        { name: "McLaren" },
        { name: "Meddon" },
        { name: "MedievalSharp" },
        { name: "Medula One" },
        { name: "Megrim" },
        { name: "Meie Script" },
        { name: "Merienda" },
        { name: "Merienda One" },
        { name: "Merriweather" },
        { name: "Merriweather Sans" },
        { name: "Metal" },
        { name: "Metal Mania" },
        { name: "Metamorphous" },
        { name: "Metrophobic" },
        { name: "Michroma" },
        { name: "Milonga" },
        { name: "Miltonian" },
        { name: "Miltonian Tattoo" },
        { name: "Miniver" },
        { name: "Miss Fajardose" },
        { name: "Modak" },
        { name: "Modern Antiqua" },
        { name: "Molengo" },
        { name: "Molle" },
        { name: "Monda" },
        { name: "Monofett" },
        { name: "Monoton" },
        { name: "Monsieur La Doulaise" },
        { name: "Montaga" },
        { name: "Montez" },
        { name: "Montserrat" },
        { name: "Montserrat Alternates" },
        { name: "Montserrat Subrayada" },
        { name: "Moul" },
        { name: "Moulpali" },
        { name: "Mountains of Christmas" },
        { name: "Mouse Memoirs" },
        { name: "Mr Bedfort" },
        { name: "Mr Dafoe" },
        { name: "Mr De Haviland" },
        { name: "Mrs Saint Delafield" },
        { name: "Mrs Sheppards" },
        { name: "Muli" },
        { name: "Mystery Quest" },
        { name: "NTR" },
        { name: "Neucha" },
        { name: "Neuton" },
        { name: "New Rocker" },
        { name: "News Cycle" },
        { name: "Niconne" },
        { name: "Nixie One" },
        { name: "Nobile" },
        { name: "Nokora" },
        { name: "Norican" },
        { name: "Nosifer" },
        { name: "Nothing You Could Do" },
        { name: "Noticia Text" },
        { name: "Noto Sans" },
        { name: "Noto Serif" },
        { name: "Nova Cut" },
        { name: "Nova Flat" },
        { name: "Nova Mono" },
        { name: "Nova Oval" },
        { name: "Nova Round" },
        { name: "Nova Script" },
        { name: "Nova Slim" },
        { name: "Nova Square" },
        { name: "Numans" },
        { name: "Nunito" },
        { name: "Odor Mean Chey" },
        { name: "Offside" },
        { name: "Old Standard TT" },
        { name: "Oldenburg" },
        { name: "Oleo Script" },
        { name: "Oleo Script Swash Caps" },
        { name: "Open Sans" },
        { name: "Open Sans Condensed" },
        { name: "Oranienbaum" },
        { name: "Orbitron" },
        { name: "Oregano" },
        { name: "Orienta" },
        { name: "Original Surfer" },
        { name: "Oswald" },
        { name: "Over the Rainbow" },
        { name: "Overlock" },
        { name: "Overlock SC" },
        { name: "Ovo" },
        { name: "Oxygen" },
        { name: "Oxygen Mono" },
        { name: "PT Mono" },
        { name: "PT Sans" },
        { name: "PT Sans Caption" },
        { name: "PT Sans Narrow" },
        { name: "PT Serif" },
        { name: "PT Serif Caption" },
        { name: "Pacifico" },
        { name: "Palanquin" },
        { name: "Palanquin Dark" },
        { name: "Paprika" },
        { name: "Parisienne" },
        { name: "Passero One" },
        { name: "Passion One" },
        { name: "Pathway Gothic One" },
        { name: "Patrick Hand" },
        { name: "Patrick Hand SC" },
        { name: "Patua One" },
        { name: "Paytone One" },
        { name: "Peddana" },
        { name: "Peralta" },
        { name: "Permanent Marker" },
        { name: "Petit Formal Script" },
        { name: "Petrona" },
        { name: "Philosopher" },
        { name: "Piedra" },
        { name: "Pinyon Script" },
        { name: "Pirata One" },
        { name: "Plaster" },
        { name: "Play" },
        { name: "Playball" },
        { name: "Playfair Display" },
        { name: "Playfair Display SC" },
        { name: "Podkova" },
        { name: "Poiret One" },
        { name: "Poller One" },
        { name: "Poly" },
        { name: "Pompiere" },
        { name: "Pontano Sans" },
        { name: "Port Lligat Sans" },
        { name: "Port Lligat Slab" },
        { name: "Pragati Narrow" },
        { name: "Prata" },
        { name: "Preahvihear" },
        { name: "Press Start 2P" },
        { name: "Princess Sofia" },
        { name: "Prociono" },
        { name: "Prosto One" },
        { name: "Puritan" },
        { name: "Purple Purse" },
        { name: "Quando" },
        { name: "Quantico" },
        { name: "Quattrocento" },
        { name: "Quattrocento Sans" },
        { name: "Questrial" },
        { name: "Quicksand" },
        { name: "Quintessential" },
        { name: "Qwigley" },
        { name: "Racing Sans One" },
        { name: "Radley" },
        { name: "Rajdhani" },
        { name: "Raleway" },
        { name: "Raleway Dots" },
        { name: "Ramabhadra" },
        { name: "Ramaraja" },
        { name: "Rambla" },
        { name: "Rammetto One" },
        { name: "Ranchers" },
        { name: "Rancho" },
        { name: "Ranga" },
        { name: "Rationale" },
        { name: "Ravi Prakash" },
        { name: "Redressed" },
        { name: "Reenie Beanie" },
        { name: "Revalia" },
        { name: "Ribeye" },
        { name: "Ribeye Marrow" },
        { name: "Righteous" },
        { name: "Risque" },
        { name: "Roboto" },
        { name: "Roboto Condensed" },
        { name: "Roboto Slab" },
        { name: "Rochester" },
        { name: "Rock Salt" },
        { name: "Rokkitt" },
        { name: "Romanesco" },
        { name: "Ropa Sans" },
        { name: "Rosario" },
        { name: "Rosarivo" },
        { name: "Rouge Script" },
        { name: "Rozha One" },
        { name: "Rubik Mono One" },
        { name: "Rubik One" },
        { name: "Ruda" },
        { name: "Rufina" },
        { name: "Ruge Boogie" },
        { name: "Ruluko" },
        { name: "Rum Raisin" },
        { name: "Ruslan Display" },
        { name: "Russo One" },
        { name: "Ruthie" },
        { name: "Rye" },
        { name: "Sacramento" },
        { name: "Sail" },
        { name: "Salsa" },
        { name: "Sanchez" },
        { name: "Sancreek" },
        { name: "Sansita One" },
        { name: "Sarina" },
        { name: "Sarpanch" },
        { name: "Satisfy" },
        { name: "Scada" },
        { name: "Scheherazade" },
        { name: "Schoolbell" },
        { name: "Seaweed Script" },
        { name: "Sevillana" },
        { name: "Seymour One" },
        { name: "Shadows Into Light" },
        { name: "Shadows Into Light Two" },
        { name: "Shanti" },
        { name: "Share" },
        { name: "Share Tech" },
        { name: "Share Tech Mono" },
        { name: "Shojumaru" },
        { name: "Short Stack" },
        { name: "Siemreap" },
        { name: "Sigmar One" },
        { name: "Signika" },
        { name: "Signika Negative" },
        { name: "Simonetta" },
        { name: "Sintony" },
        { name: "Sirin Stencil" },
        { name: "Six Caps" },
        { name: "Skranji" },
        { name: "Slabo 13px" },
        { name: "Slabo 27px" },
        { name: "Slackey" },
        { name: "Smokum" },
        { name: "Smythe" },
        { name: "Sniglet" },
        { name: "Snippet" },
        { name: "Snowburst One" },
        { name: "Sofadi One" },
        { name: "Sofia" },
        { name: "Sonsie One" },
        { name: "Sorts Mill Goudy" },
        { name: "Source Code Pro" },
        { name: "Source Sans Pro" },
        { name: "Source Serif Pro" },
        { name: "Special Elite" },
        { name: "Spicy Rice" },
        { name: "Spinnaker" },
        { name: "Spirax" },
        { name: "Squada One" },
        { name: "Sree Krushnadevaraya" },
        { name: "Stalemate" },
        { name: "Stalinist One" },
        { name: "Stardos Stencil" },
        { name: "Stint Ultra Condensed" },
        { name: "Stint Ultra Expanded" },
        { name: "Stoke" },
        { name: "Strait" },
        { name: "Sue Ellen Francisco" },
        { name: "Sunshiney" },
        { name: "Supermercado One" },
        { name: "Suranna" },
        { name: "Suravaram" },
        { name: "Suwannaphum" },
        { name: "Swanky and Moo Moo" },
        { name: "Syncopate" },
        { name: "Tangerine" },
        { name: "Taprom" },
        { name: "Tauri" },
        { name: "Teko" },
        { name: "Telex" },
        { name: "Tenali Ramakrishna" },
        { name: "Tenor Sans" },
        { name: "Text Me One" },
        { name: "The Girl Next Door" },
        { name: "Tienne" },
        { name: "Timmana" },
        { name: "Tinos" },
        { name: "Titan One" },
        { name: "Titillium Web" },
        { name: "Trade Winds" },
        { name: "Trocchi" },
        { name: "Trochut" },
        { name: "Trykker" },
        { name: "Tulpen One" },
        { name: "Ubuntu" },
        { name: "Ubuntu Condensed" },
        { name: "Ubuntu Mono" },
        { name: "Ultra" },
        { name: "Uncial Antiqua" },
        { name: "Underdog" },
        { name: "Unica One" },
        { name: "UnifrakturCook" },
        { name: "UnifrakturMaguntia" },
        { name: "Unkempt" },
        { name: "Unlock" },
        { name: "Unna" },
        { name: "VT323" },
        { name: "Vampiro One" },
        { name: "Varela" },
        { name: "Varela Round" },
        { name: "Vast Shadow" },
        { name: "Vesper Libre" },
        { name: "Vibur" },
        { name: "Vidaloka" },
        { name: "Viga" },
        { name: "Voces" },
        { name: "Volkhov" },
        { name: "Vollkorn" },
        { name: "Voltaire" },
        { name: "Waiting for the Sunrise" },
        { name: "Wallpoet" },
        { name: "Walter Turncoat" },
        { name: "Warnes" },
        { name: "Wellfleet" },
        { name: "Wendy One" },
        { name: "Wire One" },
        { name: "Yanone Kaffeesatz" },
        { name: "Yellowtail" },
        { name: "Yeseva One" },
        { name: "Yesteryear" },
        { name: "Zeyada" },
      ],
    },
  ];

  const weights = [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ];

  const getFontOptions = () => {
    return allFonts.reduce((fontList, fontGroup) => {
      const fonts = fontGroup.fonts.map((font) => {
        return {
          value: font.name,
          label: font.name,
        };
      });
      const group = {
        label: fontGroup.label,
        options: fonts,
      };
      return [...fontList, group];
    }, []);
  };

  const updateFontFamily = (value) => {
    let type;
    for (let i = 0; i < allFonts.length; i++) {
      type = allFonts[i].id;
      for (let e = 0; e < allFonts[i].fonts.length; e++) {
        if (value === allFonts[i].fonts[e].name) {
          break;
        }
      }
    }

    handleUpdateFont({
      fontType: type,
      fontFamily: value,
    });
  };

  return (
    <BaseField {...props} type="typography">
      {options.includes("fontFamily") && (
        <SelectField
          id="fontFamily"
          name={__("Font Family", "ditty-news-ticker")}
          placeholder={__("Select Font Family", "ditty-news-ticker")}
          options={getFontOptions()}
          value={value.fontFamily ? value.fontFamily : false}
          onChange={(val) => updateFontFamily(val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("fontWeight") && (
        <SelectField
          id="fontWeight"
          name={__("Font Weight", "ditty-news-ticker")}
          placeholder=" "
          options={weights}
          value={value.fontWeight ? value.fontWeight : false}
          onChange={(val) => handleUpdateFont("fontWeight", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("fontSize") && (
        <UnitField
          id="fontSize"
          name={__("Font Size", "ditty-news-ticker")}
          value={value.fontSize ? value.fontSize : false}
          onChange={(val) => handleUpdateFont("fontSize", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("lineHeight") && (
        <UnitField
          id="lineHeight"
          name={__("Line Height", "ditty-news-ticker")}
          value={value.lineHeight ? value.lineHeight : false}
          onChange={(val) => handleUpdateFont("lineHeight", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("letterSpacing") && (
        <UnitField
          id="letterSpacing"
          name={__("Letter Spacing", "ditty-news-ticker")}
          value={value.letterSpacing ? value.letterSpacing : false}
          onChange={(val) => handleUpdateFont("letterSpacing", val)}
          className="ditty-field--typography__field"
        />
      )}
    </BaseField>
  );
};

export default TypographyField;
