const { __ } = wp.i18n;
import BaseField from "./BaseField";
import SelectField from "./SelectField";
import UnitField from "./UnitField";

const TypographyField = (props) => {
  const {
    value = {},
    options = [
      "fontFamily",
      "fontWeight",
      "fontSize",
      "lineHeight",
      "letterSpacing",
    ],
    onChange,
  } = props;

  const handleUpdateFont = (key, val) => {
    let updatedValue = { ...value };
    if ("object" === typeof key) {
      updatedValue = { ...value, ...key };
    } else {
      updatedValue[key] = val;
    }
    onChange(updatedValue);
  };

  const allFonts = [
    {
      id: "standard",
      label: __("Standard Fonts", "ditty-news-ticker"),
      fonts: [
        { name: "Arial" },
        { name: "Arial Black" },
        { name: "Courier New" },
        { name: "Georgia" },
        { name: "Times New Roman" },
        { name: "Trebuchet MS" },
        { name: "Verdana" },
        { name: "Impact" },
        { name: "Lucida Console" },
        { name: "Tahoma" },
        { name: "Lucida Sans Unicode" },
        { name: "Palatino Linotype" },
        { name: "Comic Sans MS" },
      ],
    },
    {
      id: "google",
      label: __("Google Fonts", "ditty-news-ticker"),
      fonts: [
        { name: "ABeeZee", type: "sans-serif" },
        { name: "Abel", type: "sans-serif" },
        { name: "Abril Fatface", type: "serif" },
        { name: "Aclonica", type: "sans-serif" },
        { name: "Acme", type: "sans-serif" },
        { name: "Actor", type: "sans-serif" },
        { name: "Adamina", type: "serif" },
        { name: "Advent Pro", type: "sans-serif" },
        { name: "Aguafina Script", type: "serif" },
        { name: "Akronim", type: "serif" },
        { name: "Aladin", type: "serif" },
        { name: "Aldrich", type: "sans-serif" },
        { name: "Alef", type: "sans-serif" },
        { name: "Alegreya", type: "serif" },
        { name: "Alegreya SC", type: "serif" },
        { name: "Alegreya Sans", type: "sans-serif" },
        { name: "Alegreya Sans SC", type: "sans-serif" },
        { name: "Alex Brush", type: "serif" },
        { name: "Alfa Slab One", type: "serif" },
        { name: "Alice", type: "serif" },
        { name: "Alike", type: "serif" },
        { name: "Alike Angular", type: "serif" },
        { name: "Allan", type: "sans-serif" },
        { name: "Allerta", type: "sans-serif" },
        { name: "Allerta Stencil", type: "sans-serif" },
        { name: "Allura", type: "serif" },
        { name: "Almendra", type: "serif" },
        { name: "Almendra Display", type: "serif" },
        { name: "Almendra SC", type: "serif" },
        { name: "Amarante", type: "serif" },
        { name: "Amaranth", type: "sans-serif" },
        { name: "Amatic SC", type: "serif" },
        { name: "Amethysta", type: "serif" },
        { name: "Amiri", type: "serif" },
        { name: "Anaheim", type: "sans-serif" },
        { name: "Andada", type: "serif" },
        { name: "Andika", type: "sans-serif" },
        { name: "Angkor", type: "sans-serif" },
        { name: "Annie Use Your Telescope", type: "serif" },
        { name: "Anonymous Pro", type: "sans-serif" },
        { name: "Antic", type: "sans-serif" },
        { name: "Antic Didone", type: "serif" },
        { name: "Antic Slab", type: "serif" },
        { name: "Anton", type: "sans-serif" },
        { name: "Arapey", type: "serif" },
        { name: "Arbutus", type: "serif" },
        { name: "Arbutus Slab", type: "serif" },
        { name: "Architects Daughter", type: "sans-serif" },
        { name: "Archivo Black", type: "sans-serif" },
        { name: "Archivo Narrow", type: "sans-serif" },
        { name: "Arimo", type: "sans-serif" },
        { name: "Arizonia", type: "serif" },
        { name: "Armata", type: "sans-serif" },
        { name: "Artifika", type: "serif" },
        { name: "Arvo", type: "serif" },
        { name: "Asap", type: "sans-serif" },
        { name: "Asset", type: "sans-serif" },
        { name: "Astloch", type: "serif" },
        { name: "Asul", type: "sans-serif" },
        { name: "Atomic Age", type: "sans-serif" },
        { name: "Aubrey", type: "serif" },
        { name: "Audiowide", type: "sans-serif" },
        { name: "Autour One", type: "serif" },
        { name: "Average", type: "serif" },
        { name: "Average Sans", type: "sans-serif" },
        { name: "Averia Gruesa Libre", type: "sans-serif" },
        { name: "Averia Libre", type: "serif" },
        { name: "Averia Sans Libre", type: "sans-serif" },
        { name: "Averia Serif Libre", type: "serif" },
        { name: "Bad Script", type: "serif" },
        { name: "Balthazar", type: "serif" },
        { name: "Bangers", type: "sans-serif" },
        { name: "Basic", type: "sans-serif" },
        { name: "Battambang", type: "sans-serif" },
        { name: "Baumans", type: "sans-serif" },
        { name: "Bayon", type: "sans-serif" },
        { name: "Belgrano", type: "serif" },
        { name: "Belleza", type: "sans-serif" },
        { name: "BenchNine", type: "sans-serif" },
        { name: "Bentham", type: "serif" },
        { name: "Berkshire Swash", type: "serif" },
        { name: "Bevan", type: "serif" },
        { name: "Bigelow Rules", type: "sans-serif" },
        { name: "Bigshot One", type: "sans-serif" },
        { name: "Bilbo", type: "serif" },
        { name: "Bilbo Swash Caps", type: "serif" },
        { name: "Biryani", type: "sans-serif" },
        { name: "Bitter", type: "serif" },
        { name: "Black Ops One", type: "sans-serif" },
        { name: "Bokor", type: "sans-serif" },
        { name: "Bonbon", type: "serif" },
        { name: "Boogaloo", type: "sans-serif" },
        { name: "Bowlby One", type: "sans-serif" },
        { name: "Bowlby One SC", type: "sans-serif" },
        { name: "Brawler", type: "serif" },
        { name: "Bree Serif", type: "serif" },
        { name: "Bubblegum Sans", type: "sans-serif" },
        { name: "Bubbler One", type: "sans-serif" },
        { name: "Buda", type: "sans-serif" },
        { name: "Buenard", type: "serif" },
        { name: "Butcherman", type: "serif" },
        { name: "Butterfly Kids", type: "serif" },
        { name: "Cabin", type: "sans-serif" },
        { name: "Cabin Condensed", type: "sans-serif" },
        { name: "Cabin Sketch", type: "sans-serif" },
        { name: "Caesar Dressing", type: "serif" },
        { name: "Cagliostro", type: "sans-serif" },
        { name: "Calligraffitti", type: "serif" },
        { name: "Cambay", type: "sans-serif" },
        { name: "Cambo", type: "serif" },
        { name: "Candal", type: "sans-serif" },
        { name: "Cantarell", type: "sans-serif" },
        { name: "Cantata One", type: "serif" },
        { name: "Cantora One", type: "sans-serif" },
        { name: "Capriola", type: "sans-serif" },
        { name: "Cardo", type: "serif" },
        { name: "Carme", type: "sans-serif" },
        { name: "Carrois Gothic", type: "sans-serif" },
        { name: "Carrois Gothic SC", type: "sans-serif" },
        { name: "Carter One", type: "sans-serif" },
        { name: "Caudex", type: "serif" },
        { name: "Cedarville Cursive", type: "serif" },
        { name: "Ceviche One", type: "serif" },
        { name: "Changa One", type: "sans-serif" },
        { name: "Chango", type: "serif" },
        { name: "Chau Philomene One", type: "sans-serif" },
        { name: "Chela One", type: "sans-serif" },
        { name: "Chelsea Market", type: "sans-serif" },
        { name: "Chenla", type: "serif" },
        { name: "Cherry Cream Soda", type: "sans-serif" },
        { name: "Cherry Swash", type: "serif" },
        { name: "Chewy", type: "sans-serif" },
        { name: "Chicle", type: "serif" },
        { name: "Chivo", type: "sans-serif" },
        { name: "Cinzel", type: "serif" },
        { name: "Cinzel Decorative", type: "serif" },
        { name: "Clicker Script", type: "serif" },
        { name: "Coda", type: "sans-serif" },
        { name: "Coda Caption", type: "sans-serif" },
        { name: "Codystar", type: "sans-serif" },
        { name: "Combo", type: "sans-serif" },
        { name: "Comfortaa", type: "sans-serif" },
        { name: "Coming Soon", type: "serif" },
        { name: "Concert One", type: "sans-serif" },
        { name: "Condiment", type: "serif" },
        { name: "Content", type: "serif" },
        { name: "Contrail One", type: "sans-serif" },
        { name: "Convergence", type: "sans-serif" },
        { name: "Cookie", type: "serif" },
        { name: "Copse", type: "serif" },
        { name: "Corben", type: "serif" },
        { name: "Courgette", type: "serif" },
        { name: "Cousine", type: "sans-serif" },
        { name: "Coustard", type: "serif" },
        { name: "Covered By Your Grace", type: "serif" },
        { name: "Crafty Girls", type: "serif" },
        { name: "Creepster", type: "serif" },
        { name: "Crete Round", type: "serif" },
        { name: "Crimson Text", type: "serif" },
        { name: "Croissant One", type: "serif" },
        { name: "Crushed", type: "sans-serif" },
        { name: "Cuprum", type: "sans-serif" },
        { name: "Cutive", type: "serif" },
        { name: "Cutive Mono", type: "serif" },
        { name: "Damion", type: "serif" },
        { name: "Dancing Script", type: "serif" },
        { name: "Dangrek", type: "sans-serif" },
        { name: "Dawning of a New Day", type: "serif" },
        { name: "Days One", type: "sans-serif" },
        { name: "Dekko", type: "sans-serif" },
        { name: "Delius", type: "serif" },
        { name: "Delius Swash Caps", type: "serif" },
        { name: "Delius Unicase", type: "sans-serif" },
        { name: "Della Respira", type: "serif" },
        { name: "Denk One", type: "sans-serif" },
        { name: "Devonshire", type: "serif" },
        { name: "Dhurjati", type: "sans-serif" },
        { name: "Didact Gothic", type: "sans-serif" },
        { name: "Diplomata", type: "serif" },
        { name: "Diplomata SC", type: "serif" },
        { name: "Domine", type: "serif" },
        { name: "Donegal One", type: "serif" },
        { name: "Doppio One", type: "sans-serif" },
        { name: "Dorsa", type: "sans-serif" },
        { name: "Dosis", type: "sans-serif" },
        { name: "Dr Sugiyama", type: "serif" },
        { name: "Droid Sans", type: "sans-serif" },
        { name: "Droid Sans Mono", type: "sans-serif" },
        { name: "Droid Serif", type: "serif" },
        { name: "Duru Sans", type: "sans-serif" },
        { name: "Dynalight", type: "serif" },
        { name: "EB Garamond", type: "serif" },
        { name: "Eagle Lake", type: "serif" },
        { name: "Eater", type: "sans-serif" },
        { name: "Economica", type: "sans-serif" },
        { name: "Ek Mukta", type: "sans-serif" },
        { name: "Electrolize", type: "sans-serif" },
        { name: "Elsie", type: "serif" },
        { name: "Elsie Swash Caps", type: "serif" },
        { name: "Emblema One", type: "sans-serif" },
        { name: "Emilys Candy", type: "serif" },
        { name: "Engagement", type: "serif" },
        { name: "Englebert", type: "sans-serif" },
        { name: "Enriqueta", type: "serif" },
        { name: "Erica One", type: "sans-serif" },
        { name: "Esteban", type: "serif" },
        { name: "Euphoria Script", type: "serif" },
        { name: "Ewert", type: "serif" },
        { name: "Exo", type: "sans-serif" },
        { name: "Exo 2", type: "sans-serif" },
        { name: "Expletus Sans", type: "sans-serif" },
        { name: "Fanwood Text", type: "serif" },
        { name: "Fascinate", type: "sans-serif" },
        { name: "Fascinate Inline", type: "sans-serif" },
        { name: "Faster One", type: "sans-serif" },
        { name: "Fasthand", type: "serif" },
        { name: "Fauna One", type: "serif" },
        { name: "Federant", type: "serif" },
        { name: "Federo", type: "sans-serif" },
        { name: "Felipa", type: "serif" },
        { name: "Fenix", type: "serif" },
        { name: "Finger Paint", type: "serif" },
        { name: "Fira Mono", type: "sans-serif" },
        { name: "Fira Sans", type: "sans-serif" },
        { name: "Fjalla One", type: "sans-serif" },
        { name: "Fjord One", type: "serif" },
        { name: "Flamenco", type: "serif" },
        { name: "Flavors", type: "serif" },
        { name: "Fondamento", type: "serif" },
        { name: "Fontdiner Swanky", type: "serif" },
        { name: "Forum", type: "serif" },
        { name: "Francois One", type: "sans-serif" },
        { name: "Freckle Face", type: "serif" },
        { name: "Fredericka the Great", type: "serif" },
        { name: "Fredoka One", type: "sans-serif" },
        { name: "Freehand", type: "serif" },
        { name: "Fresca", type: "sans-serif" },
        { name: "Frijole", type: "sans-serif" },
        { name: "Fruktur", type: "serif" },
        { name: "Fugaz One", type: "sans-serif" },
        { name: "GFS Didot", type: "serif" },
        { name: "GFS Neohellenic", type: "sans-serif" },
        { name: "Gabriela", type: "serif" },
        { name: "Gafata", type: "sans-serif" },
        { name: "Galdeano", type: "sans-serif" },
        { name: "Galindo", type: "sans-serif" },
        { name: "Gentium Basic", type: "serif" },
        { name: "Gentium Book Basic", type: "serif" },
        { name: "Geo", type: "sans-serif" },
        { name: "Geostar", type: "serif" },
        { name: "Geostar Fill", type: "serif" },
        { name: "Germania One", type: "serif" },
        { name: "Gidugu", type: "sans-serif" },
        { name: "Gilda Display", type: "serif" },
        { name: "Give You Glory", type: "serif" },
        { name: "Glass Antiqua", type: "sans-serif" },
        { name: "Glegoo", type: "serif" },
        { name: "Gloria Hallelujah", type: "serif" },
        { name: "Goblin One", type: "sans-serif" },
        { name: "Gochi Hand", type: "serif" },
        { name: "Gorditas", type: "sans-serif" },
        { name: "Goudy Bookletter 1911", type: "serif" },
        { name: "Graduate", type: "serif" },
        { name: "Grand Hotel", type: "serif" },
        { name: "Gravitas One", type: "serif" },
        { name: "Great Vibes", type: "serif" },
        { name: "Griffy", type: "serif" },
        { name: "Gruppo", type: "sans-serif" },
        { name: "Gudea", type: "sans-serif" },
        { name: "Gurajada", type: "serif" },
        { name: "Habibi", type: "serif" },
        { name: "Halant", type: "serif" },
        { name: "Hammersmith One", type: "sans-serif" },
        { name: "Hanalei", type: "serif" },
        { name: "Hanalei Fill", type: "serif" },
        { name: "Handlee", type: "serif" },
        { name: "Hanuman", type: "serif" },
        { name: "Happy Monkey", type: "sans-serif" },
        { name: "Headland One", type: "serif" },
        { name: "Henny Penny", type: "serif" },
        { name: "Herr Von Muellerhoff", type: "serif" },
        { name: "Hind", type: "sans-serif" },
        { name: "Holtwood One SC", type: "serif" },
        { name: "Homemade Apple", type: "serif" },
        { name: "Homenaje", type: "sans-serif" },
        { name: "IM Fell DW Pica", type: "serif" },
        { name: "IM Fell DW Pica SC", type: "serif" },
        { name: "IM Fell Double Pica", type: "serif" },
        { name: "IM Fell Double Pica SC", type: "serif" },
        { name: "IM Fell English", type: "serif" },
        { name: "IM Fell English SC", type: "serif" },
        { name: "IM Fell French Canon", type: "serif" },
        { name: "IM Fell French Canon SC", type: "serif" },
        { name: "IM Fell Great Primer", type: "serif" },
        { name: "IM Fell Great Primer SC", type: "serif" },
        { name: "Iceberg", type: "sans-serif" },
        { name: "Iceland", type: "sans-serif" },
        { name: "Imprima", type: "sans-serif" },
        { name: "Inconsolata", type: "sans-serif" },
        { name: "Inder", type: "sans-serif" },
        { name: "Indie Flower", type: "serif" },
        { name: "Inika", type: "serif" },
        { name: "Irish Grover", type: "serif" },
        { name: "Istok Web", type: "sans-serif" },
        { name: "Italiana", type: "serif" },
        { name: "Italianno", type: "serif" },
        { name: "Jacques Francois", type: "serif" },
        { name: "Jacques Francois Shadow", type: "serif" },
        { name: "Jaldi", type: "sans-serif" },
        { name: "Jim Nightshade", type: "serif" },
        { name: "Jockey One", type: "sans-serif" },
        { name: "Jolly Lodger", type: "serif" },
        { name: "Josefin Sans", type: "sans-serif" },
        { name: "Josefin Slab", type: "serif" },
        { name: "Joti One", type: "sans-serif" },
        { name: "Judson", type: "serif" },
        { name: "Julee", type: "serif" },
        { name: "Julius Sans One", type: "sans-serif" },
        { name: "Junge", type: "serif" },
        { name: "Jura", type: "sans-serif" },
        { name: "Just Another Hand", type: "serif" },
        { name: "Just Me Again Down Here", type: "serif" },
        { name: "Kalam", type: "serif" },
        { name: "Kameron", type: "serif" },
        { name: "Kantumruy", type: "sans-serif" },
        { name: "Karla", type: "sans-serif" },
        { name: "Karma", type: "serif" },
        { name: "Kaushan Script", type: "serif" },
        { name: "Kavoon", type: "serif" },
        { name: "Kdam Thmor", type: "sans-serif" },
        { name: "Keania One", type: "serif" },
        { name: "Kelly Slab", type: "serif" },
        { name: "Kenia", type: "serif" },
        { name: "Khand", type: "sans-serif" },
        { name: "Khmer", type: "sans-serif" },
        { name: "Khula", type: "sans-serif" },
        { name: "Kite One", type: "sans-serif" },
        { name: "Knewave", type: "serif" },
        { name: "Kotta One", type: "serif" },
        { name: "Koulen", type: "serif" },
        { name: "Kranky", type: "serif" },
        { name: "Kreon", type: "serif" },
        { name: "Kristi", type: "serif" },
        { name: "Krona One", type: "sans-serif" },
        { name: "La Belle Aurore", type: "serif" },
        { name: "Laila", type: "serif" },
        { name: "Lakki Reddy", type: "serif" },
        { name: "Lancelot", type: "serif" },
        { name: "Lateef", type: "serif" },
        { name: "Lato", type: "sans-serif" },
        { name: "League Script", type: "serif" },
        { name: "Leckerli One", type: "serif" },
        { name: "Ledger", type: "serif" },
        { name: "Lekton", type: "sans-serif" },
        { name: "Lemon", type: "serif" },
        { name: "Libre Baskerville", type: "serif" },
        { name: "Life Savers", type: "sans-serif" },
        { name: "Lilita One", type: "serif" },
        { name: "Lily Script One", type: "serif" },
        { name: "Limelight", type: "serif" },
        { name: "Linden Hill", type: "serif" },
        { name: "Lobster", type: "serif" },
        { name: "Lobster Two", type: "serif" },
        { name: "Londrina Outline", type: "serif" },
        { name: "Londrina Shadow", type: "serif" },
        { name: "Londrina Sketch", type: "serif" },
        { name: "Londrina Solid", type: "serif" },
        { name: "Lora", type: "serif" },
        { name: "Love Ya Like A Sister", type: "sans-serif" },
        { name: "Loved by the King", type: "serif" },
        { name: "Lovers Quarrel", type: "serif" },
        { name: "Luckiest Guy", type: "sans-serif" },
        { name: "Lusitana", type: "serif" },
        { name: "Lustria", type: "serif" },
        { name: "Macondo", type: "serif" },
        { name: "Macondo Swash Caps", type: "serif" },
        { name: "Magra", type: "sans-serif" },
        { name: "Maiden Orange", type: "serif" },
        { name: "Mako", type: "sans-serif" },
        { name: "Mallanna", type: "sans-serif" },
        { name: "Mandali", type: "sans-serif" },
        { name: "Marcellus", type: "serif" },
        { name: "Marcellus SC", type: "serif" },
        { name: "Marck Script", type: "serif" },
        { name: "Margarine", type: "serif" },
        { name: "Marko One", type: "serif" },
        { name: "Marmelad", type: "sans-serif" },
        { name: "Martel", type: "serif" },
        { name: "Martel Sans", type: "sans-serif" },
        { name: "Marvel", type: "sans-serif" },
        { name: "Mate", type: "serif" },
        { name: "Mate SC", type: "serif" },
        { name: "Maven Pro", type: "sans-serif" },
        { name: "McLaren", type: "serif" },
        { name: "Meddon", type: "serif" },
        { name: "MedievalSharp", type: "serif" },
        { name: "Medula One", type: "serif" },
        { name: "Megrim", type: "sans-serif" },
        { name: "Meie Script", type: "serif" },
        { name: "Merienda", type: "serif" },
        { name: "Merienda One", type: "serif" },
        { name: "Merriweather", type: "serif" },
        { name: "Merriweather Sans", type: "sans-serif" },
        { name: "Metal", type: "serif" },
        { name: "Metal Mania", type: "serif" },
        { name: "Metamorphous", type: "serif" },
        { name: "Metrophobic", type: "sans-serif" },
        { name: "Michroma", type: "sans-serif" },
        { name: "Milonga", type: "serif" },
        { name: "Miltonian", type: "serif" },
        { name: "Miltonian Tattoo", type: "serif" },
        { name: "Miniver", type: "serif" },
        { name: "Miss Fajardose", type: "serif" },
        { name: "Modak", type: "serif" },
        { name: "Modern Antiqua", type: "serif" },
        { name: "Molengo", type: "sans-serif" },
        { name: "Molle", type: "serif" },
        { name: "Monda", type: "sans-serif" },
        { name: "Monofett", type: "serif" },
        { name: "Monoton", type: "serif" },
        { name: "Monsieur La Doulaise", type: "serif" },
        { name: "Montaga", type: "serif" },
        { name: "Montez", type: "serif" },
        { name: "Montserrat", type: "sans-serif" },
        { name: "Montserrat Alternates", type: "sans-serif" },
        { name: "Montserrat Subrayada", type: "sans-serif" },
        { name: "Moul", type: "serif" },
        { name: "Moulpali", type: "serif" },
        { name: "Mountains of Christmas", type: "serif" },
        { name: "Mouse Memoirs", type: "sans-serif" },
        { name: "Mr Bedfort", type: "serif" },
        { name: "Mr Dafoe", type: "serif" },
        { name: "Mr De Haviland", type: "serif" },
        { name: "Mrs Saint Delafield", type: "serif" },
        { name: "Mrs Sheppards", type: "serif" },
        { name: "Muli", type: "sans-serif" },
        { name: "Mystery Quest", type: "serif" },
        { name: "NTR", type: "sans-serif" },
        { name: "Neucha", type: "sans-serif" },
        { name: "Neuton", type: "serif" },
        { name: "New Rocker", type: "serif" },
        { name: "News Cycle", type: "sans-serif" },
        { name: "Niconne", type: "serif" },
        { name: "Nixie One", type: "serif" },
        { name: "Nobile", type: "sans-serif" },
        { name: "Nokora", type: "serif" },
        { name: "Norican", type: "serif" },
        { name: "Nosifer", type: "serif" },
        { name: "Nothing You Could Do", type: "serif" },
        { name: "Noticia Text", type: "serif" },
        { name: "Noto Sans", type: "sans-serif" },
        { name: "Noto Serif", type: "serif" },
        { name: "Nova Cut", type: "serif" },
        { name: "Nova Flat", type: "serif" },
        { name: "Nova Mono", type: "sans-serif" },
        { name: "Nova Oval", type: "serif" },
        { name: "Nova Round", type: "serif" },
        { name: "Nova Script", type: "serif" },
        { name: "Nova Slim", type: "serif" },
        { name: "Nova Square", type: "serif" },
        { name: "Numans", type: "sans-serif" },
        { name: "Nunito", type: "sans-serif" },
        { name: "Odor Mean Chey", type: "serif" },
        { name: "Offside", type: "sans-serif" },
        { name: "Old Standard TT", type: "serif" },
        { name: "Oldenburg", type: "serif" },
        { name: "Oleo Script", type: "serif" },
        { name: "Oleo Script Swash Caps", type: "serif" },
        { name: "Open Sans", type: "sans-serif" },
        { name: "Open Sans Condensed", type: "sans-serif" },
        { name: "Oranienbaum", type: "serif" },
        { name: "Orbitron", type: "sans-serif" },
        { name: "Oregano", type: "serif" },
        { name: "Orienta", type: "sans-serif" },
        { name: "Original Surfer", type: "serif" },
        { name: "Oswald", type: "sans-serif" },
        { name: "Over the Rainbow", type: "serif" },
        { name: "Overlock", type: "serif" },
        { name: "Overlock SC", type: "serif" },
        { name: "Ovo", type: "serif" },
        { name: "Oxygen", type: "sans-serif" },
        { name: "Oxygen Mono", type: "sans-serif" },
        { name: "PT Mono", type: "sans-serif" },
        { name: "PT Sans", type: "sans-serif" },
        { name: "PT Sans Caption", type: "sans-serif" },
        { name: "PT Sans Narrow", type: "sans-serif" },
        { name: "PT Serif", type: "serif" },
        { name: "PT Serif Caption", type: "serif" },
        { name: "Pacifico", type: "serif" },
        { name: "Palanquin", type: "sans-serif" },
        { name: "Palanquin Dark", type: "sans-serif" },
        { name: "Paprika", type: "serif" },
        { name: "Parisienne", type: "serif" },
        { name: "Passero One", type: "serif" },
        { name: "Passion One", type: "serif" },
        { name: "Pathway Gothic One", type: "sans-serif" },
        { name: "Patrick Hand", type: "serif" },
        { name: "Patrick Hand SC", type: "serif" },
        { name: "Patua One", type: "serif" },
        { name: "Paytone One", type: "sans-serif" },
        { name: "Peddana", type: "serif" },
        { name: "Peralta", type: "serif" },
        { name: "Permanent Marker", type: "serif" },
        { name: "Petit Formal Script", type: "serif" },
        { name: "Petrona", type: "serif" },
        { name: "Philosopher", type: "sans-serif" },
        { name: "Piedra", type: "serif" },
        { name: "Pinyon Script", type: "serif" },
        { name: "Pirata One", type: "serif" },
        { name: "Plaster", type: "serif" },
        { name: "Play", type: "sans-serif" },
        { name: "Playball", type: "serif" },
        { name: "Playfair Display", type: "serif" },
        { name: "Playfair Display SC", type: "serif" },
        { name: "Podkova", type: "serif" },
        { name: "Poiret One", type: "serif" },
        { name: "Poller One", type: "serif" },
        { name: "Poly", type: "serif" },
        { name: "Pompiere", type: "serif" },
        { name: "Pontano Sans", type: "sans-serif" },
        { name: "Port Lligat Sans", type: "sans-serif" },
        { name: "Port Lligat Slab", type: "serif" },
        { name: "Pragati Narrow", type: "sans-serif" },
        { name: "Prata", type: "serif" },
        { name: "Preahvihear", type: "serif" },
        { name: "Press Start 2P", type: "serif" },
        { name: "Princess Sofia", type: "serif" },
        { name: "Prociono", type: "serif" },
        { name: "Prosto One", type: "sans-serif" },
        { name: "Puritan", type: "sans-serif" },
        { name: "Purple Purse", type: "serif" },
        { name: "Quando", type: "serif" },
        { name: "Quantico", type: "sans-serif" },
        { name: "Quattrocento", type: "serif" },
        { name: "Quattrocento Sans", type: "sans-serif" },
        { name: "Questrial", type: "sans-serif" },
        { name: "Quicksand", type: "sans-serif" },
        { name: "Quintessential", type: "serif" },
        { name: "Qwigley", type: "serif" },
        { name: "Racing Sans One", type: "sans-serif" },
        { name: "Radley", type: "serif" },
        { name: "Rajdhani", type: "sans-serif" },
        { name: "Raleway", type: "sans-serif" },
        { name: "Raleway Dots", type: "sans-serif" },
        { name: "Ramabhadra", type: "sans-serif" },
        { name: "Ramaraja", type: "serif" },
        { name: "Rambla", type: "sans-serif" },
        { name: "Rammetto One", type: "serif" },
        { name: "Ranchers", type: "serif" },
        { name: "Rancho", type: "serif" },
        { name: "Ranga", type: "serif" },
        { name: "Rationale", type: "sans-serif" },
        { name: "Ravi Prakash", type: "serif" },
        { name: "Redressed", type: "serif" },
        { name: "Reenie Beanie", type: "serif" },
        { name: "Revalia", type: "serif" },
        { name: "Ribeye", type: "serif" },
        { name: "Ribeye Marrow", type: "serif" },
        { name: "Righteous", type: "serif" },
        { name: "Risque", type: "serif" },
        { name: "Roboto", type: "sans-serif" },
        { name: "Roboto Condensed", type: "sans-serif" },
        { name: "Roboto Slab", type: "serif" },
        { name: "Rochester", type: "serif" },
        { name: "Rock Salt", type: "serif" },
        { name: "Rokkitt", type: "serif" },
        { name: "Romanesco", type: "serif" },
        { name: "Ropa Sans", type: "sans-serif" },
        { name: "Rosario", type: "serif" },
        { name: "Rosarivo", type: "serif" },
        { name: "Rouge Script", type: "serif" },
        { name: "Rozha One", type: "serif" },
        { name: "Rubik Mono One", type: "sans-serif" },
        { name: "Rubik One", type: "sans-serif" },
        { name: "Ruda", type: "sans-serif" },
        { name: "Rufina", type: "serif" },
        { name: "Ruge Boogie", type: "serif" },
        { name: "Ruluko", type: "sans-serif" },
        { name: "Rum Raisin", type: "sans-serif" },
        { name: "Ruslan Display", type: "serif" },
        { name: "Russo One", type: "sans-serif" },
        { name: "Ruthie", type: "serif" },
        { name: "Rye", type: "serif" },
        { name: "Sacramento", type: "serif" },
        { name: "Sail", type: "serif" },
        { name: "Salsa", type: "serif" },
        { name: "Sanchez", type: "serif" },
        { name: "Sancreek", type: "serif" },
        { name: "Sansita One", type: "serif" },
        { name: "Sarina", type: "serif" },
        { name: "Sarpanch", type: "sans-serif" },
        { name: "Satisfy", type: "serif" },
        { name: "Scada", type: "sans-serif" },
        { name: "Scheherazade", type: "serif" },
        { name: "Schoolbell", type: "serif" },
        { name: "Seaweed Script", type: "serif" },
        { name: "Sevillana", type: "serif" },
        { name: "Seymour One", type: "sans-serif" },
        { name: "Shadows Into Light", type: "serif" },
        { name: "Shadows Into Light Two", type: "serif" },
        { name: "Shanti", type: "sans-serif" },
        { name: "Share", type: "serif" },
        { name: "Share Tech", type: "sans-serif" },
        { name: "Share Tech Mono", type: "sans-serif" },
        { name: "Shojumaru", type: "serif" },
        { name: "Short Stack", type: "serif" },
        { name: "Siemreap", type: "serif" },
        { name: "Sigmar One", type: "serif" },
        { name: "Signika", type: "sans-serif" },
        { name: "Signika Negative", type: "sans-serif" },
        { name: "Simonetta", type: "serif" },
        { name: "Sintony", type: "sans-serif" },
        { name: "Sirin Stencil", type: "serif" },
        { name: "Six Caps", type: "sans-serif" },
        { name: "Skranji", type: "serif" },
        { name: "Slabo 13px", type: "serif" },
        { name: "Slabo 27px", type: "serif" },
        { name: "Slackey", type: "serif" },
        { name: "Smokum", type: "serif" },
        { name: "Smythe", type: "serif" },
        { name: "Sniglet", type: "sans-serif" },
        { name: "Snippet", type: "sans-serif" },
        { name: "Snowburst One", type: "serif" },
        { name: "Sofadi One", type: "serif" },
        { name: "Sofia", type: "serif" },
        { name: "Sonsie One", type: "serif" },
        { name: "Sorts Mill Goudy", type: "serif" },
        { name: "Source Code Pro", type: "sans-serif" },
        { name: "Source Sans Pro", type: "sans-serif" },
        { name: "Source Serif Pro", type: "serif" },
        { name: "Special Elite", type: "serif" },
        { name: "Spicy Rice", type: "serif" },
        { name: "Spinnaker", type: "sans-serif" },
        { name: "Spirax", type: "serif" },
        { name: "Squada One", type: "sans-serif" },
        { name: "Sree Krushnadevaraya", type: "serif" },
        { name: "Stalemate", type: "serif" },
        { name: "Stalinist One", type: "serif" },
        { name: "Stardos Stencil", type: "serif" },
        { name: "Stint Ultra Condensed", type: "sans-serif" },
        { name: "Stint Ultra Expanded", type: "sans-serif" },
        { name: "Stoke", type: "serif" },
        { name: "Strait", type: "sans-serif" },
        { name: "Sue Ellen Francisco", type: "serif" },
        { name: "Sunshiney", type: "serif" },
        { name: "Supermercado One", type: "sans-serif" },
        { name: "Suranna", type: "serif" },
        { name: "Suravaram", type: "serif" },
        { name: "Suwannaphum", type: "serif" },
        { name: "Swanky and Moo Moo", type: "serif" },
        { name: "Syncopate", type: "sans-serif" },
        { name: "Tangerine", type: "serif" },
        { name: "Taprom", type: "serif" },
        { name: "Tauri", type: "sans-serif" },
        { name: "Teko", type: "sans-serif" },
        { name: "Telex", type: "sans-serif" },
        { name: "Tenali Ramakrishna", type: "serif" },
        { name: "Tenor Sans", type: "sans-serif" },
        { name: "Text Me One", type: "sans-serif" },
        { name: "The Girl Next Door", type: "serif" },
        { name: "Tienne", type: "serif" },
        { name: "Timmana", type: "sans-serif" },
        { name: "Tinos", type: "serif" },
        { name: "Titan One", type: "serif" },
        { name: "Titillium Web", type: "sans-serif" },
        { name: "Trade Winds", type: "serif" },
        { name: "Trocchi", type: "serif" },
        { name: "Trochut", type: "serif" },
        { name: "Trykker", type: "serif" },
        { name: "Tulpen One", type: "serif" },
        { name: "Ubuntu", type: "sans-serif" },
        { name: "Ubuntu Condensed", type: "sans-serif" },
        { name: "Ubuntu Mono", type: "sans-serif" },
        { name: "Ultra", type: "serif" },
        { name: "Uncial Antiqua", type: "serif" },
        { name: "Underdog", type: "serif" },
        { name: "Unica One", type: "serif" },
        { name: "UnifrakturCook", type: "serif" },
        { name: "UnifrakturMaguntia", type: "serif" },
        { name: "Unkempt", type: "serif" },
        { name: "Unlock", type: "sans-serif" },
        { name: "Unna", type: "serif" },
        { name: "VT323", type: "sans-serif" },
        { name: "Vampiro One", type: "serif" },
        { name: "Varela", type: "sans-serif" },
        { name: "Varela Round", type: "sans-serif" },
        { name: "Vast Shadow", type: "serif" },
        { name: "Vesper Libre", type: "serif" },
        { name: "Vibur", type: "serif" },
        { name: "Vidaloka", type: "serif" },
        { name: "Viga", type: "sans-serif" },
        { name: "Voces", type: "sans-serif" },
        { name: "Volkhov", type: "serif" },
        { name: "Vollkorn", type: "serif" },
        { name: "Voltaire", type: "sans-serif" },
        { name: "Waiting for the Sunrise", type: "serif" },
        { name: "Wallpoet", type: "serif" },
        { name: "Walter Turncoat", type: "serif" },
        { name: "Warnes", type: "sans-serif" },
        { name: "Wellfleet", type: "serif" },
        { name: "Wendy One", type: "sans-serif" },
        { name: "Wire One", type: "sans-serif" },
        { name: "Yanone Kaffeesatz", type: "sans-serif" },
        { name: "Yellowtail", type: "serif" },
        { name: "Yeseva One", type: "serif" },
        { name: "Yesteryear", type: "serif" },
        { name: "Zeyada", type: "serif" },
      ],
    },
  ];

  const weights = [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ];

  const getFontOptions = () => {
    return allFonts.reduce((fontList, fontGroup) => {
      const fonts = fontGroup.fonts.map((font) => {
        return {
          value: font.name,
          label: font.name,
        };
      });
      const group = {
        label: fontGroup.label,
        options: fonts,
      };
      return [...fontList, group];
    }, []);
  };

  const updateFontFamily = (value) => {
    let type;
    for (let i = 0; i < allFonts.length; i++) {
      for (let e = 0; e < allFonts[i].fonts.length; e++) {
        if (value === allFonts[i].fonts[e].name) {
          type = allFonts[i].id;
          break;
        }
      }
    }

    handleUpdateFont({
      fontType: type,
      fontFamily: value,
    });
  };

  return (
    <BaseField {...props} type="typography">
      {options.includes("fontFamily") && (
        <SelectField
          id="fontFamily"
          name={__("Font Family", "ditty-news-ticker")}
          placeholder={__("Select Font Family", "ditty-news-ticker")}
          options={getFontOptions()}
          value={value.fontFamily ? value.fontFamily : false}
          onChange={(val) => updateFontFamily(val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("fontWeight") && (
        <SelectField
          id="fontWeight"
          name={__("Font Weight", "ditty-news-ticker")}
          placeholder=" "
          options={weights}
          value={value.fontWeight ? value.fontWeight : false}
          onChange={(val) => handleUpdateFont("fontWeight", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("fontSize") && (
        <UnitField
          id="fontSize"
          name={__("Font Size", "ditty-news-ticker")}
          value={value.fontSize ? value.fontSize : false}
          onChange={(val) => handleUpdateFont("fontSize", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("lineHeight") && (
        <UnitField
          id="lineHeight"
          name={__("Line Height", "ditty-news-ticker")}
          value={value.lineHeight ? value.lineHeight : false}
          onChange={(val) => handleUpdateFont("lineHeight", val)}
          className="ditty-field--typography__field"
        />
      )}
      {options.includes("letterSpacing") && (
        <UnitField
          id="letterSpacing"
          name={__("Letter Spacing", "ditty-news-ticker")}
          value={value.letterSpacing ? value.letterSpacing : false}
          onChange={(val) => handleUpdateFont("letterSpacing", val)}
          className="ditty-field--typography__field"
        />
      )}
    </BaseField>
  );
};

export default TypographyField;
